---
sidebar: sidebar 
permalink: cascade-replication.html 
keywords: replicate, cascade, cascade replication, cascade deployment, data protection, volume replication, replicate data protection volume 
summary: 复制数据保护卷或级联卷数据复制、将数据保护扩展到三级系统或迁移数据。 
---
= 在BlueXP  工作负载出厂时复制数据保护卷
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
复制数据保护卷或级联卷数据复制、将数据保护扩展到三级系统或迁移数据。

.关于此任务
BlueXP  工作负载工厂支持复制数据保护卷、也称为_级 联部署_。级联部署_由一系列关系组成、其中、一个源卷镜像到一个二级卷(第一个跃点)、而该二级卷镜像到一个三级卷(第二个跃点)。如果二级卷不可用，您可以同步主卷和三级卷之间的关系，而无需执行新的基线传输。

对于运行ONTAP 9.6及更高版本的ONTAP文件系统、FSx支持此功能。请参阅 link:https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html#snapmirror-disaster-recovery-relationships["兼容ONTAP版本的ONTAP文档"^]。

详细了解 link:https://docs.netapp.com/us-en/ontap/data-protection/supported-deployment-config-concept.html#how-cascade-deployments-work["级联部署的工作原理"^]。

.开始之前
开始之前、请考虑以下事项：

* 请注意、级联配置中的卷重新同步可能需要较长时间。
* 如果此关系的源卷是一个数据保护卷、并且是另一个关系的目标、则不支持反转此复制关系。
* 支持数据保护卷的一个副本(或第二个跃点)。最佳做法不是为数据保护卷创建第二个副本(或第三个跃点)。


.步骤
. 使用其中一个登录link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["控制台体验"^]。
. 在存储中，选择*转至存储清单*。
. 在*FSx for FS* ONTAP选项卡中，选择包含要复制的卷的文件系统的三点菜单，然后选择*Manage*。
. 从文件系统概述中，选择*Volumes*选项卡。
. 在卷表中、选择一个或多个数据保护卷(DP/复制的卷)、然后选择*复制数据*。
. 在复制数据页面上的复制目标下、提供以下内容：
+
.. *FSx for ONTAP file system*：为目标FSx for ONTAP文件系统选择ONTAP文件系统的凭据、区域和FSx名称。
.. * Storage VM名称*：从下拉菜单中选择Storage VM。
.. *卷名*：目标卷名称将自动生成，格式如下 `{OriginalVolumeName}_copy`。您可以使用自动生成的卷名称或输入其他卷名称。
.. *用例*：选择以下复制用例之一。根据所选的使用情形、工作负载出厂时会根据最佳实践使用建议的值填充表单。您可以接受建议的值、也可以在填写表单后进行更改。
+
*** 迁移：将数据传输到目标FSx for ONTAP文件系统
*** 热灾难恢复：确保关键工作负载的高可用性和快速灾难恢复
*** 冷灾难恢复或归档灾难恢复：
+
**** 冷灾难恢复：使用更长的恢复时间目标(RTO)和恢复点对象(RPO)来降低成本
**** 归档：复制数据以实现长期存储和合规性


*** 其他


.. *分层策略*：为目标卷中存储的数据选择分层策略。对于您选择的使用情形、此层策略默认为建议的层策略。
+
使用工作负载出厂控制台创建卷时、默认分层策略为_Balanced (Auto)_。有关卷分层策略的详细信息、请参阅 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["卷存储容量"^] AWS FSx for NetApp ONTAP文档中的。请注意、工作负载工厂在工作负载工厂控制台中使用基于用例的名称来执行分层策略、并将FSx for ONTAP分层策略名称括在圆括号中。

+
如果您选择了迁移用例、则工作负载出厂时会自动选择将源卷的分层策略复制到目标卷。您可以取消选择以复制此层策略、并选择一个适用于选定进行复制的卷的层策略。

.. *最大传输速率*：选择*受限*并输入最大传输速率(MB/秒)或者，选择*Unlimited (无限制)*。
+
如果没有限制、网络和应用程序性能可能会下降。或者、对于关键工作负载(例如、主要用于灾难恢复的工作负载)、我们建议对用于ONTAP文件系统的FSx使用无限传输速率。



. 在复制设置下、提供以下内容：
+
.. *复制间隔*：选择从源卷向目标卷传输快照的频率。
.. *长期保留*：(可选)启用快照以进行长期保留。长期保留使业务服务即使在站点完全瘫痪时也能继续运行、从而支持应用程序使用二级副本透明地进行故障转移。
+
如果启用长期保留、请选择现有策略或创建新策略以定义要复制的快照以及要保留的数量。

+

NOTE: 长期保留需要匹配的源标签和目标标签。如果需要、工作负载工厂可以为您创建缺少的标签。

+
*** *选择现有策略*：从下拉菜单中选择现有策略。
*** *创建新策略*：提供以下内容：
+
**** *策略名称*：输入策略名称。
**** 可选：启用不可删除的快照。
+
***** 选择*启用不可更改的快照*以防止在保留期间删除此策略中创建的快照。
***** 以小时、天、月或年为单位设置*保留期限*。


**** *Snapshot策略*：在表中，选择快照策略频率和要保留的副本数。您可以选择多个快照策略。






. 选择 * 创建 * 。


.结果
复制的一个或多个卷将进行复制并显示在目标FSx for ONTAP文件系统的*复制关系*选项卡中。
