---
sidebar: sidebar 
permalink: change-tiering-policy.html 
keywords: tiering policy, change tier, change tiers, tier policy update 
summary: 更改NetApp Workload Factory 中的分层策略，将数据从高性能主存储层重新分配到二级容量池存储层。 
---
= 在NetApp Workload Factory 中更改卷的分层策略
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
在NetApp Workload Factory 中，您可以更改分层策略，以自动将数据从高性能主存储层重新分配到二级容量池存储层。

.关于此任务
您可以随时更改卷的层策略。此层策略按卷定义。

确定数据的存储位置会对您节省成本产生影响。

FSx for ONTAP具有两个存储卷数据的层：

* *SSD存储层*：此主存储层用于存储您最常访问的数据、也称为_hot_ data。在主存储层存储数据比在二级存储层存储数据成本更高。
* *容量池存储层*：此二级存储层用于归档数据或不常访问的数据、也称为_col_data。


有关存储层的详细信息、请参见 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-storage-capacity.html#storage-tiers["管理存储容量"^] AWS for FSx for NetApp ONTAP文档中的。

.开始之前
更改分层策略之前、请查看可用的分层策略。

* *Balanced (Auto)*：使用用户界面创建卷时的默认分层策略。在冷却期结束后、将经常访问的数据保留在SSD存储层中、并将不经常访问的数据和快照分层到容量池存储层。建议用于常规主要工作负载。
* *成本优化(全部)*：将所有快照和数据分层到容量池存储层。建议用于次要目标。
* *性能优化(仅限Snapshot)*：仅将快照数据分层到容量池存储层。建议用于任务关键型数据库等低延迟工作负载。
* *无*：将卷数据保留在SSD存储层中、防止将其移动到容量池存储层。


请注意、某些分层策略具有关联的最短冷却期、该冷却期用于设置卷中的用户数据必须保持非活动状态的时间或_冷却天数_、才能将数据视为"冷"数据并移至容量池存储层。冷却期从数据写入磁盘时开始。

.步骤
. 使用其中一个登录link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["控制台体验"^]。
. 在存储图块中，选择*转到存储*。
. 从存储菜单中，选择 *FSx for ONTAP*。
. 从 *FSx for ONTAP* 中，选择要更新卷的文件系统的操作菜单，然后选择 *管理*。
. 从文件系统概述中，选择*Volumes*选项卡。
. 从“卷”选项卡中，选择要更改分层策略的卷的操作菜单。
. 选择*高级操作*，然后选择*更改分层策略*。
. 在更改分层策略页面上、选择复制源卷的分层策略或选择以下分层策略之一：
+
** *平衡(自动)*：输入冷却天数。
** *成本优化(全部)*
** *性能优化(仅限Snapshot)*：输入冷却天数。
** * 无 *


. 选择 * 应用 * 。

