---
sidebar: sidebar 
permalink: configuration-analysis.html 
keywords: configuration issues, issues, improve, analyze, storage configuration, Amazon FSx for NetApp ONTAP, FSx for ONTAP, recommendation, recommendations 
summary: NetApp Workload Factory 定期分析Amazon FSx for NetApp ONTAP文件系统配置，以确定是否存在任何问题。 
---
= FSx for ONTAP文件系统的配置分析
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory 定期分析Amazon FSx for NetApp ONTAP文件系统配置，以确定是否存在任何问题。当发现问题时，Workload Factory 会向您展示问题所在，并解释需要进行哪些更改以确保您的文件系统存储达到最佳性能、成本效益并符合最佳实践。

主要功能包括：

* 每日配置分析
* 自动最佳实践验证
* 主动可观察性
* 从洞察力到行动
* AWS架构完善的Framework Advisor




== 架构良好的状态

在文件系统级别的 Workload Factory 控制台中，列出了所有 FSx for ONTAP文件系统的良好架构状态。架构良好的状态分为“问题”、“未分析”或“架构良好”。选择良好架构状态会将您重定向到文件系统内的良好架构状态选项卡，您可以在其中找到良好架构分数、配置类别以及文件系统的所有配置。

精心设计的得分:: 得分包括当前分析的所有配置、并以百分比形式显示。25%的分数表示25%的文件系统配置设计良好。
配置类别:: 文件系统配置会根据AWS精心设计的框架的以下五大支柱按类别进行组织。
+
--
* _Reliability _：确保工作负载正确一致地执行其预期功能、即使发生中断也是如此。例如、FSx for ONTAP备份就是一个配置示例。
* _Security_：强调通过风险评估和缓解策略保护数据、系统和资产。
* _卓越运营_：专注于提供最优架构和业务价值。
* _成本优化_：旨在提供业务价值、同时最大程度地降低成本。
* _Performance效率_：侧重于高效利用资源来满足系统要求、并在需求变化时保持最佳性能。


--




== 分析要求

要进行完整的文件系统分析，必须执行以下操作：

* 关联链接。链路连接使 Workload Factory 能够分析所有文件系统配置，例如数据保护和性能。
+
link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["了解如何关联现有链接或创建并关联新链接"](英文)

* 在您的 AWS 账户中授予_查看、规划和分析_权限。
+
link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["了解如何为AWS帐户授予权限"^]



.下一步行动
link:improve-configurations.html["实施架构良好的文件系统配置"]
