---
sidebar: sidebar 
permalink: configuration-analysis.html 
keywords: configuration issues, issues, improve, analyze, storage configuration, Amazon FSx for NetApp ONTAP, FSx for ONTAP, recommendation, recommendations 
summary: NetApp Workload Factory 定期分析 Amazon FSx for NetApp ONTAP 文件系统配置，以确定是否存在任何配置问题。 
---
= FSx for ONTAP文件系统的配置分析
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory 定期分析 Amazon FSx for NetApp ONTAP 文件系统配置，以确定是否存在任何配置问题。当发现问题时，Workload Factory 会向您展示问题所在，并解释需要更改的内容，以确保您的文件系统存储实现最佳性能、成本效益和符合最佳实践。

主要功能包括：

* 每日配置分析
* 自动最佳实践验证
* 主动可观察性
* 从洞察力到行动
* AWS架构完善的Framework Advisor




[[how-it-works]]
== 工作原理

Workload Factory 每天分析在 Amazon FSx for NetApp ONTAP 文件系统部署上运行的工作负载。该分析提供了精心设计的状态、见解和建议。

每日分析完成后，配置在 Well-architected 仪表板中显示为"优化"或"未优化"。您可以找到总优化分数、按类别划分的配置问题以及配置问题和建议列表。您可以查看配置问题的建议。有些问题可以由 Workload Factory 自动修复，而其他问题则需要手动干预。在这种情况下，Workload Factory 会提供详细说明，以帮助您实施建议的更改。

您可以忽略不适用于您环境的配置分析。这样可以避免不必要的警报和不准确的优化结果。

您还可以用简单的语言创建自定义规则，以根据组织的标准和 NetApp 最佳实践验证您的环境。通过试运行测试规则，然后安排它们在您的环境中运行。link:https://docs.netapp.com/us-en/console-well-architected/learn-custom-rules.html["详细了解自定义规则"^]。

您还可以用简单的语言创建自定义规则，以根据组织的标准和 NetApp 最佳实践验证您的环境。通过试运行测试规则，然后安排它们在您的环境中运行。

link:https://docs.netapp.com/us-en/console-well-architected/learn-custom-rules.html["详细了解自定义规则"^]。



[[why-it-matters]]
== 为什么很重要

Workload Factory 通过将持续评估与建议见解和补救措施相结合，将最佳实践应用于大型存储、数据库和 VMware 环境。在 Workload Factory 控制台中应用的自动修复可减少人为错误，确保统一管理，并保持整个工作负载基础架构的性能和可靠性。



[[analysis-requirements]]
== 分析要求

要进行完整的文件系统分析，必须执行以下操作：

* 关联链接。链路连接使 Workload Factory 能够分析所有文件系统配置，例如数据保护和性能。
+
link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["了解如何关联现有链接或创建并关联新链接"](英文)

* 在您的 AWS 账户中授予_查看、规划和分析_权限。
+
link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["了解如何为AWS帐户授予权限"^]





[[best-practices-and-recommendations-for-storage-workloads]]
== 存储工作负载的最佳实践和建议

精心设计的仪表板根据 ONTAP 最佳实践和 AWS Well-Architected Framework 评估存储配置。该评估还提出了改进和修复建议。

架构完善的分析将配置归类为框架的以下支柱：_reliability_、_security_、_operational excellence_、_cost optimization_ 和 _performance efficiency_。



[[reliability]]
=== 可靠性

可靠性可确保工作负载正确、一致地执行其预期功能，即使在发生中断时也是如此。

* *卷备份*
+
备份卷有助于支持数据保留和合规性需求。使用卷备份为数据设置自动备份和保留。

* *Snapshot 策略*
+
安排本地快照以实现高效备份和快速恢复。快照是卷的即时时间点映像。此建议不适用于数据库环境。

* *应用程序一致性快照*
+
对于数据库环境，请使用应用程序一致性快照与 NetApp SnapCenter 配合，以便在特定时间点为卷数据拍摄准确、可靠的快照。这可确保您的应用程序顺利运行和数据安全。SnapCenter 使备份更轻松，并帮助您快速、正确地还原数据，从而减少停机时间并保护您最重要的工作负载。

* *跨区域复制*
+
跨区域复制可确保将您的数据复制到另一个 AWS 区域，从而提高数据持久性和可用性。设置跨区域复制以支持灾难恢复和合规性。

* *SSD 容量余量*
+
SSD 存储层容量不应超过 80% 的利用率。这可能会影响对容量池存储层的数据读取和写入，并影响文件系统的吞吐量。当容量耗尽时，数据卷将变为只读。尝试写入新数据的服务也会失败。

* *复制策略标签*
+
源卷的快照策略标签和复制策略标签必须匹配，以确保数据可靠性。

* *文件对象容量*
+
应提高文件容量阈值，以避免达到卷容量限制。低文件容量（索引节点）会阻止向卷写入其他数据。Workload Factory 建议将文件容量利用率保持在 80% 以下，以允许创建新文件。





[[security]]
=== 安全性

安全强调通过风险评估和缓解策略保护数据、系统和资产。

* *勒索软件保护（ARP/AI）*
+
NetApp Autonomous Ransomware Protection with AI (ARP/AI) 有助于保护您的卷免受勒索软件威胁。Workload Factory 建议为所有卷启用 ARP/AI。

* *未经授权的 iSCSI 卷访问*
+
使用 iSCSI 服务应用程序数据的卷不应同时允许 NAS 访问。Workload Factory 建议限制 iSCSI 卷使用任何其他协议。





[[operational-excellence]]
=== 卓越运营

卓越运营侧重于提供最佳架构和业务价值。

* *自动容量管理*
+
应启用自动容量管理，以定期确保 SSD 层不超过阈值。

* *卷容量余量*
+
Workload Factory 建议卷容量不超过 80% 的利用率。这可能会影响对应用程序的数据读取和写入。卷容量可以手动增加，也可以使用卷自动增长功能自动增加。

* *FlexCache 写入模式*
+
为了获得最佳性能，Workload Factory 建议使用最适合您的工作负载的缓存关系写入模式。写入绕行模式为具有小文件的读取密集型工作负载提供更好的性能，而写回模式为具有大文件的写入密集型工作负载提供更好的性能。

* *FlexCache 副本大小*
+
Workload Factory 建议在缓存卷上启用卷自动调整大小和清理，以保持最佳大小，并将缓存集中在热数据上，以实现最高效率。

* *主机可见容量报告*
+
Workload Factory 建议启用主机可见容量报告，以便更好地了解卷级别的存储使用情况。

* *操作系统 (OS) 类型*
+
Workload Factory 建议确保 ONTAP LUN 操作系统 (OS) 类型值与操作系统分区方案匹配，以实现 I/O 对齐。配置不正确可能会降低性能。

* *块设备空间管理*
+
Workload Factory 建议为数据库主机实例使用的 LUN 配置块设备空间设置，以防止写入失败并提高 FSx for ONTAP 的空间效率。此配置适用于精简配置卷的建议设置组合：空间预留、空间分配和部分预留。

* *精简配置*
+
Workload Factory 建议为托管数据库实例的 FSx for ONTAP 卷配置精简配置。这种方法允许存储比实际可用容量更多的逻辑数据。





[[cost-optimization]]
=== 成本优化

成本优化可帮助您在保持低成本的同时为业务创造最大价值。

* *冷数据分层*
+
启用冷数据分层以降低 SSD 存储层利用率。Workload Factory 建议将分层策略应用于专注于一般数据存储的每个卷。对于数据库卷，我们建议在适当情况下启用冷数据分层。FSx for ONTAP 持续扫描数据以查找冷数据，并将其无中断地移动到容量池层。

* *存储效率*
+
启用存储效率功能（数据缩减、压缩和重复数据删除），以优化存储利用率并降低 SSD 层成本。

* *备份过期时间*
+
Workload Factory 建议删除已删除卷的所有手动创建的备份，以及任何超过两周的备份。这些备份不会自动过期，如果您不再需要它们用于 SLA 或恢复，可能会增加成本并增加复杂性。

* *Snapshot 过期*
+
Workload Factory 建议删除不再需要的旧快照或手动创建的快照。移除它们可以降低成本并减少冗余，特别是在您的 SLA 或恢复需求不需要它们的情况下。

* *非活动块设备*
+
在块设备未使用七天后，Workload Factory 建议归档块设备数据或删除未使用的块设备以降低成本。

* *过度配置的 SSD 容量*
+
过度配置的 SSD 容量层会增加不必要的成本。Workload Factory 建议减少 SSD 层容量，同时保持 20% 的可用空间缓冲区。减少操作需要数小时到数天，在此期间不支持其他文件系统操作。

* *非活动 NAS 卷*
+
配置分析可识别未主动使用的 NAS 卷，并建议删除或归档这些卷以降低成本。





[[performance-efficiency]]
=== 性能效率

性能效率可帮助您确保存储资源得到有效利用，并确保工作负载以最佳方式运行。

* *FlexGroup 卷重新平衡*
+
Workload Factory 建议重新平衡您的 FlexGroup 卷以提高效率。横向扩展后，整个卷的容量和工作负载活动可能会变得不均匀。

* *FlexVol 卷重新平衡*
+
Workload Factory 建议重新平衡您的 FlexVol 卷以提高效率。横向扩展后，整个卷的容量和工作负载活动可能会变得不均匀。



.下一步行动
link:improve-configurations.html["实施架构良好的文件系统配置"]
