---
sidebar: sidebar 
permalink: create-file-system.html 
keywords: create, FSx file system, ONTAP file system, workload factory, storage 
summary: 使用BlueXP  工作负载工厂、您可以创建适用于ONTAP文件系统的FSx、以添加和管理卷以及其他数据服务。 
---
= 在BlueXP  工作负载出厂时为ONTAP文件系统创建FSx
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
使用 BlueXP 工作负载工厂，您可以创建第一代和第二代 FSx for ONTAP 文件系统来添加和管理卷和附加数据服务。

.关于此任务
在创建文件系统过程中会创建Storage VM和安全组。

.开始之前
在创建FSx for ONTAP文件系统之前、您需要：

* IAM角色的ARN、为工作负载工厂提供创建FSx for ONTAP文件系统所需的权限。link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["了解如何为AWS帐户授予权限"^](英文)
* 要为其创建 FSX for ONTAP 实例的区域和 VPC 信息。




== 创建FSx for ONTAP文件系统

您可以使用_Quick cre成_或_Advanced cre成_来创建FSx for ONTAP文件系统。您还可以使用CodeBox中提供的以下工具：REST API、CloudFormation和Terraform。link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox["了解如何使用CodeBox实现自动化"^](英文)


NOTE: 使用来自CodeBox的Terraform时、您复制或下载的代码会隐藏 `fsxadmin` 和 `vsadmin` 密码。运行代码时、您需要重新输入密码。

[role="tabbed-block"]
====
.快速创建
--
通过快速创建、您可以使用建议的最佳实践配置。创建FSx for ONTAP文件系统后、您可以更改大多数设置。

第二代 FSx for ONTAP 文件系统是快速创建的默认部署类型，除非所选区域不支持第二代 FSx for ONTAP 文件系统。

.步骤
. 使用其中一个登录link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["控制台体验"^]。
. 在存储中，选择*Create FSx for FS* ONTAP。
. 在"Create FSx for ONTAP (创建FSx for Windows)"页面上、选择*快速创建*。
+
您也可以加载已保存的配置。

. 在文件系统常规配置下、提供以下内容：
+
.. *AWS凭据*：选择在工作负载出厂时添加AWS凭据、或在无凭据的情况下继续操作。
.. *文件系统名称*：输入文件系统的名称。
.. *区域和VPC*：为文件系统选择区域和VPC。
.. *部署类型*：选择部署类型。
+
*** 单可用性区域(单可用性区域、单可用性)部署：通过监控硬件故障来提供可用性、并在发生故障时自动更换基础架构组件。通过在可用性区域中自动复制数据以防止其发生组件故障、实现高持久性。
+
对于高性能工作负载，或者当工作负载从小规模开始并逐步扩展到 72 GB/s 的吞吐量和 240 万 IOPS 时，建议使用此配置。

*** 多可用性区域(Multi-AZ)部署：即使可用性区域不可用、也能持续提供数据。多可用性文件系统专为业务关键型生产工作负载而设计、这些工作负载要求共享ONTAP文件数据具有高可用性、并需要具有跨可用性区域内置复制功能的存储。
+
对于需要高达 6 GB/s 吞吐量或 200,000 IOPS 的工作负载，建议使用此单 HA 对配置。



.. *标记*：您可以选择最多添加50个标记。


. 在*文件系统详细信息*下，提供以下内容：
+
.. *SSD存储容量*：输入存储容量并选择存储容量单位。
+
*** 对于第一代部署，您无法在创建文件系统后减少容量。
*** 对于第二代部署，您可以在创建文件系统后增加容量。


.. * ONTAP凭据*：可选。输入您的ONTAP用户名和密码。可以现在或稍后设置密码。
+
如果您提供的用户不是fsxadmin用户、而稍后您需要重置fsxadmin密码、则可以从AWS控制台执行此操作。

.. *SMB/CCIFS设置*：可选。如果您计划使用SMB/CCIFS协议访问卷、则必须在文件系统创建期间为Storage VM配置Active Directory。提供为此文件系统创建的Storage VM的以下详细信息。
+
... *要加入的Active Directory域*：输入Active Directory的完全限定域名(FQDN)。
... *DNS IP地址*：最多输入三个DNS IP地址，以逗号分隔。
... *SMB服务器NetBIOS名称*：输入要为Storage VM创建的Active Directory计算机对象的SMB服务器NetBIOS名称。这是Active Directory中此Storage VM的名称。
... *用户名*：输入现有Active Directory中服务帐户的用户名。
+
请勿包含域前缀或后缀。对于 `EXAMPLE\ADMIN`，请使用 `ADMIN`。

... *密码*：输入服务帐户的密码。
... *组织单位*：(可选)输入要为FSx for ONTAP创建计算机帐户的组织单位的名称。OU是要加入文件系统的组织单位的可分辨路径名称。
... *委派管理员组*：(可选)输入Active Directory中可管理文件系统的组的名称。
+
如果您使用的是AWS Managed Microsoft AD、则必须指定一个组、例如AWS Delegated FSx Administrators、AWS Delegated Administrators或具有对OU的委派权限的自定义组。

+
如果您要加入自行管理的广告、请使用广告中的组名称。默认组为 `Domain Admins`。





. 打开*Summary (摘要)*以查看您定义的配置。如果需要、您可以在保存或创建文件系统之前更改此时的任何设置。
. 保存或创建文件系统。


如果您创建了文件系统，现在可以在*Inventory*页中查看FSx for ONTAP文件系统。

--
.高级创建
--
使用Advanced create、您可以设置所有配置选项、包括可用性、安全性、备份和维护。

.步骤
. 使用其中一个登录link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["控制台体验"^]。
. 在存储中，选择*Create FSx for FS* ONTAP。
. 在"Create FSx for ONTAP (创建FSx for Windows)"页面上、选择*高级创建*。
+
您也可以加载已保存的配置。

. 在文件系统常规配置下、提供以下内容：
+
.. *AWS凭据*：选择在工作负载出厂时添加AWS凭据、或在无凭据的情况下继续操作。
.. *文件系统名称*：输入文件系统的名称。
.. *区域和VPC*：为文件系统选择区域和VPC。
.. *部署类型*：选择部署类型和文件系统生成。第二代文件系统的可用性取决于所选的区域。如果所选区域不支持第二代 FSx for ONTAP 文件系统，则部署类型将切换为第一代。
+
*** 单可用性区域(单可用性区域、单可用性)部署：通过监控硬件故障来提供可用性、并在发生故障时自动更换基础架构组件。通过在可用性区域中自动复制数据以防止其发生组件故障、实现高持久性。
+
*文件系统生成*：选择以下之一：

+
**** *第二代*：此配置适用于高性能工作负载，或当工作负载从小规模开始并逐步扩展到 72 GB/s 的吞吐量和 240 万 IOPS 时。
**** *第一代*：此配置非常适合需要高达 4 GB/s 或 160,000 IOPS 的工作负载。第一代文件系统只能增加容量。


*** 多可用性区域(Multi-AZ)部署：即使可用性区域不可用、也能持续提供数据。多可用性文件系统专为业务关键型生产工作负载而设计、这些工作负载要求共享ONTAP文件数据具有高可用性、并需要具有跨可用性区域内置复制功能的存储。
+
*文件系统生成*：选择以下之一：

+
**** *第二代*：对于需要高达 6 GB/s 吞吐量或 200,000 IOPS 的工作负载，建议使用此单 HA 对配置。在多可用区和第二代文件系统中，容量可以根据工作负载需求增加或减少。
**** *第一代*：此配置非常适合需要高达 4 GB/s 或 160,000 IOPS 的工作负载。第一代文件系统只能增加容量。




.. *标记*：您可以选择最多添加50个标记。


. 在文件系统详细信息下、提供以下内容：
+
.. *SSD存储容量*：输入存储容量并选择存储容量单位。
+
*** 对于第一代部署，您无法在创建文件系统后减少容量。
*** 对于第二代部署，您可以调整容量。


.. *每个 HA 对的吞吐容量*：选择每个 HA 对的吞吐容量。第一代文件系统仅支持一个 HA 对。
.. *预配置 IOPS*：选择以下选项之一：
+
*** *自动*：对于自动操作，每创建 1 GiB，就会添加 3 IOPS。
*** *用户配置*：对于用户配置，输入 IOPS 值。


.. * ONTAP凭据*：可选。输入您的ONTAP用户名和密码。可以现在或稍后设置密码。
+
如果您提供的用户不是fsxadmin用户、而稍后您需要重置fsxadmin密码、则可以从AWS控制台执行此操作。

.. * Storage VM凭据*：可选。输入您的用户名。密码可以特定于此文件系统、也可以使用为ONTAP凭据输入的相同密码。可以现在或稍后设置密码。
.. *SMB/CCIFS设置*：可选。如果您计划使用SMB/CCIFS协议访问卷、则必须在文件系统创建期间为Storage VM配置Active Directory。提供为此文件系统创建的Storage VM的以下详细信息。
+
... *要加入的Active Directory域*：输入Active Directory的完全限定域名(FQDN)。
... *DNS IP地址*：最多输入三个DNS IP地址，以逗号分隔。
... *SMB服务器NetBIOS名称*：输入要为Storage VM创建的Active Directory计算机对象的SMB服务器NetBIOS名称。这是Active Directory中此Storage VM的名称。
... *用户名*：输入现有Active Directory中服务帐户的用户名。
+
请勿包含域前缀或后缀。对于 `EXAMPLE\ADMIN`，请使用 `ADMIN`。

... *密码*：输入服务帐户的密码。
... *组织单位*：(可选)输入要为FSx for ONTAP创建计算机帐户的组织单位的名称。OU是要加入文件系统的组织单位的可分辨路径名称。
... *委派管理员组*：(可选)输入Active Directory中可管理文件系统的组的名称。
+
如果您使用的是AWS Managed Microsoft AD、则必须指定一个组、例如AWS Delegated FSx Administrators、AWS Delegated Administrators或具有对OU的委派权限的自定义组。

+
如果您要加入自行管理的广告、请使用广告中的组名称。默认组为 `Domain Admins`。





. 在"网络和安全"下、提供以下内容：
+
.. *安全组*：创建或使用现有安全组。
+
对于新的安全组、请参见<<安全组详细信息,安全组详细信息>>了解安全组协议、端口和角色的说明。

.. *可用性区域*：选择可用性区域和子网。
+
*** 对于集群配置节点1：选择可用性区域和子网。
*** 对于集群配置节点2：选择可用性区域和子网。


.. *vPC路由表*：选择VPC路由表以启用客户端对卷的访问。
.. *端点IP地址范围*：选择VPC*以外的*浮动IP地址范围或*输入IP地址范围*并输入IP地址范围。
.. *加密*：从下拉列表中选择加密密钥名称。


. 在备份和维护下、提供以下内容：
+
.. *FSx for ONTAP Backup*：默认情况下启用每日自动备份。如果需要、请禁用。
+
... *自动备份保留期限*：输入自动备份的保留天数。
... *每日自动备份窗口*:选择*No Preferences*(已为您选择每日备份开始时间)或*Select start time for daily backups*并指定开始时间。


.. *每周维护窗口*:选择*No Preferences*(为您选择每周维护窗口开始时间)或*Select start time for 30 minute每周维护窗口*并指定开始时间。


. 保存或创建文件系统。


如果您创建了文件系统，现在可以在*Inventory*页中查看FSx for ONTAP文件系统。

--
====


== 安全组详细信息

下表提供了安全组详细信息、包括协议、端口和角色。

[]
====
[cols="2,2,4a"]
|===
| 协议 | 端口 | 角色 


| SSH | 22  a| 
SSH 访问集群管理 LIF 或节点管理 LIF 的 IP 地址



| TCP | 80  a| 
对集群管理LIF IP地址的网页访问权限



| TCP/UDP | 111  a| 
远程过程调用 NFS



| TCP/UDP | 135  a| 
远程过程调用 CIFS



| UDP | 137  a| 
CIFS的NetBIOS名称解析



| TCP/UDP | 139  a| 
用于 CIFS 的 NetBIOS 服务会话



| TCP | 443  a| 
对集群管理LIF或SVM管理LIF的IP地址进行ONTAP REST API访问



| TCP | 445  a| 
Microsoft SMB/CIFS over TCP （通过 TCP ）和 NetBIOS 成帧



| TCP/UDP | 635  a| 
NFS 挂载



| TCP | 749  a| 
Kerberos



| TCP/UDP | 2049  a| 
NFS 服务器守护进程



| TCP | 3260  a| 
通过 iSCSI 数据 LIF 进行 iSCSI 访问



| TCP/UDP | 4045  a| 
NFS 锁定守护进程



| TCP/UDP | 4046  a| 
NFS 的网络状态监视器



| UDP | 4049  a| 
NFS配额协议



| TCP | 10000  a| 
网络数据管理协议(NDMP)和NetApp SnapMirror集群间通信



| TCP | 11104  a| 
管理NetApp SnapMirror集群间通信



| TCP | 11105  a| 
使用集群间 LIF 进行 SnapMirror 数据传输



| TCP/UDP | 161-162  a| 
简单网络管理协议(Simple Network Management Protocol、SNMP)



| 所有 ICMP | 全部  a| 
Ping 实例

|===
====
.下一步行动
通过存储清单中的文件系统，您可以 link:create-volume.html["创建卷"]管理FSx for ONTAP文件系统并设置 link:data-protection-overview.html["数据保护"] 资源。
