---
sidebar: sidebar 
permalink: create-storage-vm.html 
keywords: create storage VM, create svm 
summary: '您可以创建FSx for ONTAP Storage VM (SVM)、以便在BlueXP  工作负载工厂中为工作负载提供存储和数据服务。' 
---
= 为FSx for ONTAP文件系统创建Storage VM
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
为FSx for ONTAP文件系统创建一个Storage VM (SVM)、以便在BlueXP  工作负载工厂中以虚拟方式访问工作负载的存储和数据服务。

.关于此任务
Storage VM是一种隔离的文件服务器、可用于访问工作负载出厂存储中每个工作负载的数据。每个SVM都有自己的管理凭据和端点、用于管理和访问数据。

通过SVM、在访问FSx for ONTAP中的数据时、客户端和工作站会使用SVM的端点(IP地址)挂载SVM托管的卷、CIFS或SMB共享或iSCSI LUN。

.开始之前
验证每个文件系统支持的Storage VM数量。有关每个文件系统的最大SVM数量、请参见 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-svms.html#max-svms["管理FSx for ONTAP Storage Virtual Machine"^] AWS文档中的。



== 创建Storage VM

您可以从工作负载出厂控制台创建Storage VM。您还可以使用CodeBox中提供的以下工具：REST API、CloudFormation和Terraform。link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox["了解如何使用CodeBox实现自动化"^](英文)


NOTE: 使用来自CodeBox的Terraform时、您复制或下载的代码会隐藏 `fsxadmin` 和 `vsadmin` 密码。运行代码时、您需要重新输入密码。

.步骤
. 使用其中一个登录link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["控制台体验"^]。
. 在存储中，选择*转至存储清单*。
. 在FSx for ONTAP选项卡中、选择要创建Storage VM的文件系统的三点菜单、然后选择*创建Storage VM*。
. 在Storage VM页面上的Storage VM配置下、提供以下内容：
+
.. *名称*：输入Storage VM的名称。
.. * Storage VM凭据*：为此Storage VM的用户提供密码 `vsadmin` 或使用文件系统的 `fsxadmin` 用户凭据。
.. *根卷安全模式*：根据访问数据的客户端类型选择根卷安全模式- UNIX (Linux客户端)、NTFS (Windows客户端)或混合。
.. *标记*：您可以选择最多添加50个标记。


. 选择 * 创建 * 。

