---
sidebar: sidebar 
permalink: create-volume.html 
keywords: create volume, FSx for ONTAP volume 
summary: 在BlueXP  工作负载出厂时设置FSx for ONTAP文件系统后、您可以为ONTAP卷创建FSx。 
---
= 在BlueXP  工作负载出厂时创建FSx for ONTAP卷
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
设置FSx for ONTAP文件系统后、您可以在BlueXP  工作负载出厂时为ONTAP卷创建FSx。

.关于此任务
FSx for ONTAP卷是一种虚拟资源、用于对数据进行分组、确定数据的存储方式以及确定对数据的访问类型。卷不会占用文件系统存储容量。存储在卷中的数据主要占用SSD存储。根据卷的分层策略、数据可能还会占用容量池存储。您可以在创建卷时设置其大小、并可稍后更改其大小。

卷可能会使用以下协议：

* CIFS：适用于Windows操作系统的文件存储协议
* NFS：适用于Unix操作系统的文件存储协议
* iSCSI：块存储协议


.开始之前
创建卷之前、请查看以下前提条件：

* 工作负载出厂时必须具有FSx for ONTAP文件系统。
* 您必须具有Storage VM。
* 要访问协议、请完成以下操作：
+
** 要配置对卷的访问权限，您必须 link:manage-links.html["关联链接"]。如果您没有现有链接，请 link:create-link.html["创建链接"]。要关联文件系统中的链接，请选择*Account name*下的*Associate link*。链接关联后、返回此操作。
** 您必须为所选协议(CIFS、NFS或iSCSI)配置访问权限。




.步骤
. 使用其中一个登录link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["控制台体验"^]。
. 在存储中，选择*转至存储清单*。
. 在*FSx for FS* ONTAP选项卡中，选择要创建卷的文件系统的三点菜单，然后选择*Manage*。
. 从*Overview*选项卡中，选择*Create volume*。
. 在Create volume页面上的General Details下、提供以下详细信息：
+
.. *卷名称*：输入卷的名称。
.. * Storage VM名称*：(可选)输入Storage VM名称。
.. *卷样式*：选择* FlexVol *或* FlexGroup *卷。
+
默认情况下、FlexVol卷模式处于选中状态。

+
FlexGroup卷大小取决于成分卷的数量。每个成分卷需要100 GiB。

.. *卷大小*：输入卷大小和单位。
+
(可选)启用卷自动增长。当您选择*文件访问*作为卷访问类型时，此选项可用。

.. *标记*：您可以选择最多添加50个标记。


. 在"Access"(仅适用于具有关联链接的文件系统)下、提供以下详细信息：
+
.. *访问类型*：选择*文件访问*或*块访问*。用于配置卷访问的其他字段因您的选择而异。
+
*** *文件访问*：允许多个授权用户和设备使用SMB/CCIFS、NFS或双(SMB/NFS)协议访问卷。
+
填写以下字段以设置对卷的文件访问权限。

+
.... *NFS导出策略*：提供以下详细信息以提供NFS访问：
+
..... *访问控制*：从下拉菜单中选择*自定义导出策略*、*现有导出策略*或*无法访问卷*。
..... *导出策略名称*:
+
如果选择了自定义导出策略、请从下拉菜单中选择现有策略名称。

+
如果选择了现有导出策略、请输入新的策略名称。

..... *添加导出策略规则*：对于自定义导出策略、您可以选择向策略中添加导出策略规则。


.... *CIFS share*：输入CIFS共享名称以提供SMB访问。


*** *块访问*：允许运行关键业务应用程序的主机使用iSCSI协议访问卷。
+
填写以下字段以设置对卷的块访问。

+
.... *iSCSI配置*：提供以下详细信息以配置iSCSI以对卷进行块访问。
+
..... 选择*创建新启动程序组*或*映射现有启动程序组*。
..... 从下拉菜单中选择*主机操作系统*。
..... 输入新启动程序组的*启动程序组名称*。
..... 在Host Initiators下、添加一个或多个iSCSI限定名称(iSCSI限定名称、IQN)主机启动程序。








. 在效率和保护下、提供以下详细信息：
+
.. *存储效率*：禁用或启用存储效率。
+
可通过利用ONTAP的重复数据删除和数据压缩功能来实现存储效率。重复数据删除可消除重复的数据块。数据压缩可压缩数据块，以减少所需的物理存储量。

.. *Snapshot policy*：选择快照策略以指定快照的频率和保留时间。
+
以下是AWS的默认策略。对于自定义快照策略、必须关联一个链接。

+
`default`:: 此策略会按照以下计划自动创建快照、并删除最早的快照副本、以便为较新的副本腾出空间：
+
--
*** 每小时过五分钟创建最多六个每小时快照。
*** 星期一到星期六午夜后10分钟最多创建两个每日快照。
*** 每个星期日午夜后15分钟创建的每周快照数最多为两个。
+

NOTE: 快照时间基于文件系统的时区、默认为协调世界时(UTC)。有关更改时区的信息、请参阅 link:https://library.netapp.com/ecmdocs/ECMP1155684/html/GUID-E26E4C94-DF74-4E31-A6E8-1D2D2287A9A1.html["显示和设置系统时区"^] NetApp支持文档中的。



--
`default-1weekly`:: 此策略的工作方式与此策略相同 `default` 、只是仅保留每周计划中的一个快照。
`none`:: 此策略不会创建任何快照。您可以将此策略分配给卷、以防止自动创建快照。


.. *分层策略*：为卷中存储的数据选择分层策略。
+
使用用户界面创建卷时、默认的层策略为自动。有关卷分层策略的详细信息、请参阅 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["卷存储容量"^] AWS FSx for NetApp ONTAP文档中的。



. 在高级配置下、提供以下内容：
+
.. *接合路径*：在Storage VM的命名空间中输入卷的挂载位置。默认接合路径为 `/<volume-name>`。
.. *聚合列表*：仅适用于FlexGroup卷。添加或删除聚合。最小聚合数为1。
.. *成分卷数*：仅适用于FlexGroup卷。输入每个聚合的成分卷数。每个成分卷需要100 GiB。


. 选择 * 创建 * 。


.结果
已启动卷创建。创建后、新卷将显示在"Volumes"(卷)选项卡中。
