---
sidebar: sidebar 
permalink: create-link.html 
keywords: connect, connection, link, lambda link, associate link, create link, authenticate link 
summary: 您可以创建和管理链接、以便在BlueXP  工作负载工厂帐户与一个或多个FSx for ONTAP文件系统之间提供信任关系和连接。 
---
= 使用Lamba链接连接到FSx for ONTAP文件系统
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
要执行高级ONTAP管理操作、您需要在工作负载工厂帐户与一个或多个FSx for ONTAP文件系统之间建立连接。建立连接包括关联新的和现有的Lamb编制 链路以及对链路进行身份验证。通过链接关联、您可以直接从FSx for ONTAP文件系统监控和管理某些无法通过AWS FSx for ONTAP API获得的功能。

link:links-overview.html["了解有关链接的更多信息"](英文)

.关于此任务
链接利用AWS Lambode执行代码以响应事件、并自动管理该代码所需的计算资源。您创建的链接属于您的NetApp帐户、它们与AWS帐户相关联。

定义FSx for ONTAP文件系统时、您可以在帐户中创建链接。该链接将用于该文件系统、并且可供其他FSx for ONTAP文件系统使用。您也可以稍后关联文件系统的链接。

链路需要身份验证。您可以使用存储在工作负载出厂凭据服务中的凭据或存储在AWS密码管理器中的凭据进行真实链接。每个链路仅支持一种身份验证方法。例如、如果您选择使用AWS专有信息管理器进行链接身份验证、则以后无法更改此身份验证方法。


NOTE: 使用Connector时不支持AWS的"ConnectOR"管理器。



== 关联新链接

关联新链接包括创建和关联。

在此工作流程中，您有两种创建链接的选项 - 自动或手动。要创建链接、您需要在AWS帐户中启动AWS CloudFormation堆栈。

* 自动：通过工作负载工厂创建具有自动注册功能的链接。自动创建的链接需要令牌才能实现工作负载工厂自动化、CloudFormation代码生命周期较短。只能使用最多六个小时。
* 手动：使用 Codebox 中的 CloudFormation 或 Terraform 创建手动注册的链接。代码会保留，以便您有更多时间完成操作。当与不同的团队(如安全和开发运营团队)合作时、这很有用、因为他们可能首先需要授予完成链接创建所需的权限。


.开始之前
* 您应考虑使用哪种链接创建选项。
* 您需要在工作负载工厂中至少有一个FSx for ONTAP文件系统。要发现或创建 FSx for ONTAP 文件系统，您必须拥有一个具有 FSx for ONTAP 实例权限的 AWS 账户，并且link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html#overview["在工作负载出厂时添加凭据"^]具有存储管理的_只读_或_读/写_权限。
* 必须在与 FSx for ONTAP 文件系统关联的安全组中打开以下端口以实现链路连接。
+
** 对于工作负载工厂控制台：端口 443 (HTTPS)
** 对于 CloudShell：端口 22 (SSH)


* 使用CloudFormation堆栈添加链接时、您的AWS帐户必须具有以下权限：
+
[%collapsible]
====
[source, json]
----
"cloudformation:GetTemplateSummary",
"cloudformation:CreateStack",
"cloudformation:DeleteStack",
"cloudformation:DescribeStacks",
"cloudformation:ListStacks",
"cloudformation:DescribeStackEvents",
"cloudformation:ListStackResources",
"ec2:DescribeSubnets",
"ec2:DescribeSecurityGroups",
"ec2:DescribeVpcs",
"iam:ListRoles",
"iam:GetRolePolicy",
"iam:GetRole",
"iam:DeleteRolePolicy",
"iam:CreateRole",
"iam:DetachRolePolicy",
"iam:PassRole",
"iam:PutRolePolicy",
"iam:DeleteRole",
"iam:AttachRolePolicy",
"lambda:AddPermission",
"lambda:RemovePermission",
"lambda:InvokeFunction",
"lambda:GetFunction",
"lambda:CreateFunction",
"lambda:DeleteFunction",
"lambda:TagResource",
"codestar-connections:GetSyncConfiguration",
"ecr:BatchGetImage",
"ecr:GetDownloadUrlForLayer"
----
====


[role="tabbed-block"]
====
.自动创建
--
使用CloudFormation在工作负载工厂中自动创建和注册链接。

.步骤
. 使用其中一个登录link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["控制台体验"^]。
. 在存储中，选择*转至存储清单*。
. 在*FSx for ONTAP Link*选项卡中，选择要关联链接的文件系统的三点菜单，然后选择*Associate link*。
. 在关联链接对话框中，选择*创建新链接*，然后选择*继续*。
. 在"Create Link"页面上、提供以下内容：
+
.. *链接名称*：输入要用于此链接的名称。此名称在您的帐户中必须是唯一的。
.. *AWS SeslogManager*：可选。允许工作负载工厂从AWS密码管理器提取FSx for ONTAP访问凭据。
+
链路部署堆栈会将以下默认机密管理器ARN正则表达式添加到Lamb代 权限策略中： `arn:aws:secretsmanager:<link_deployment_region>:<link_deployment_account_id>:secret:FSxSecret*`。

+
您可以根据默认权限创建机密、也可以为链接策略分配自定义权限。

+
*将VPC专用端点配置到AWS秘密管理器*默认处于禁用状态。选择此选项将使用VPC专用端点存储此密钥、而不是将其存储在本地。

.. *链接权限*：选择以下链接权限选项之一：
+
*** *自动*：选择此选项，以便 AWS CloudFormation 或 Terraform 代码自动创建 Lambda 权限策略和执行角色。
*** *用户提供*：选择此选项可将指定的 Lambda 执行角色及其附加的策略分配给 Lambda 链接。Lambda需要以下权限。 `secretsmanager:GetSecretValue`仅当您启用 AWS Secrets Manager 时才需要权限。
+
[source, json]
----
"ec2:CreateNetworkInterface",
"ec2:DescribeNetworkInterfaces",
"ec2:DeleteNetworkInterface",
"ec2:AssignPrivateIpAddresses",
"ec2:UnassignPrivateIpAddresses",
"secretsmanager:GetSecretValue"
----
+
在文本框中输入 Lambda 执行角色 ARN。



.. *标记*：您可以选择添加要与此链接关联的任何标记、以便更轻松地对资源进行分类。例如、您可以添加一个标记、用于将此链接标识为由FSx for ONTAP文件系统使用。
+
系统会根据FSx for ONTAP文件系统自动检索AWS帐户以及帐户、位置和安全组的其他信息。



. 选择 * 创建 * 。
+
此时将显示重定向到CloudFormation对话框、并说明如何从AWS CloudFormation服务创建链接。

. 选择*继续*以打开AWS管理控制台、然后登录到此FSx for ONTAP文件系统的AWS帐户。
. 在Quick create堆栈页面的"Capabilities"下、选择*我确认AWS CloudFormation可能会创建IAM资源*。
+
请注意、在启动CloudFormation模板时、系统会向Lambdation授予三个权限。工作负载工厂在使用链接时会使用这些权限。

+
[source, json]
----
"lambda:InvokeFunction",
"lambda:GetFunction",
"lambda:UpdateFunctionCode"
----
. 选择*创建堆栈*，然后选择*继续*。
+
您可以从事件页面监控链路创建状态。此过程不应超过5分钟。

. 返回到工作负载出厂界面、您将看到此链接与FSx for ONTAP文件系统关联。


--
.手动创建
--
使用此选项，您可以提取链接的 ARN 并在此处报告。工作负载出厂时会手动为您注册此链接。您可以使用 Codebox 中的两个基础设施即代码 (IaC) 工具创建链接：CloudFormation 或 Terraform。

.步骤
. 使用其中一个登录link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["控制台体验"^]。
. 在存储中，选择*转至存储清单*。
. 在*FSx for ONTAP Link*选项卡中，选择要关联链接的文件系统的三点菜单，然后选择*Associate link*。
. 在关联链接对话框中，选择*创建新链接*，然后选择*继续*。
. 在"Create Link"页面上、提供以下内容：
+
.. *链接名称*：输入要用于此链接的名称。此名称在您的帐户中必须是唯一的。
.. *AWS SeslogManager*：可选。允许工作负载工厂从AWS密码管理器提取FSx for ONTAP访问凭据。
+
链路部署堆栈会将以下默认机密管理器ARN正则表达式添加到Lamb代 权限策略中： `arn:aws:secretsmanager:<link_deployment_region>:<link_deployment_account_id>:secret:FSxSecret*`。

+
您可以根据默认权限创建机密、也可以为链接策略分配自定义权限。

+
*将VPC专用端点配置到AWS秘密管理器*默认处于禁用状态。选择此选项将使用VPC专用端点存储此密钥、而不是将其存储在本地。

.. *链接权限*：选择以下链接权限选项之一：
+
*** *自动*：选择此选项，以便 AWS CloudFormation 或 Terraform 代码自动创建 Lambda 权限策略和执行角色。
*** *用户提供*：选择此选项可将指定的 Lambda 执行角色及其附加的策略分配给 Lambda 链接。Lambda需要以下权限。 `secretsmanager:GetSecretValue`仅当您启用 AWS Secrets Manager 时才需要权限。
+
[source, json]
----
"ec2:CreateNetworkInterface",
"ec2:DescribeNetworkInterfaces",
"ec2:DeleteNetworkInterface",
"ec2:AssignPrivateIpAddresses",
"ec2:UnassignPrivateIpAddresses"
"secretsmanager:GetSecretValue"
----
+
在文本框中输入 Lambda 执行角色 ARN。



.. *标记*：您可以选择添加要与此链接关联的任何标记、以便更轻松地对资源进行分类。例如、您可以添加一个标记、用于将此链接标识为由FSx for ONTAP文件系统使用。
.. *链接注册*：选择下拉箭头以展开有关如何从 AWS CloudFormation 服务或使用 Terraform 注册链接的说明。按照说明进行操作。
+
请注意、在启动CloudFormation模板时、系统会向Lambdation授予三个权限。工作负载工厂在使用链接时会使用这些权限。

+
[source, json]
----
"lambda:InvokeFunction",
"lambda:GetFunction",
"lambda:UpdateFunctionCode"
----
+
成功创建堆栈后、将Lamb编制ARN粘贴到文本框中。

.. 系统会根据FSx for ONTAP文件系统自动检索AWS帐户以及帐户、位置和安全组的其他信息。


. 选择 * 创建 * 。
+
您可以从事件页面监控链路创建状态。此过程不应超过5分钟。

. 返回到工作负载出厂界面、您将看到此链接与FSx for ONTAP文件系统关联。


--
====
.结果
您创建的链接与FSx for ONTAP文件系统关联。您可以执行高级ONTAP操作。



== 将现有链接与FSx for ONTAP文件系统相关联

创建链接后、请将其与一个或多个FSx for ONTAP文件系统相关联。

.步骤
. 使用其中一个登录link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["控制台体验"^]。
. 在存储中，选择*转至存储清单*。
. 在*FSx for ONTAP Link*选项卡中，选择要关联链接的文件系统的三点菜单，然后选择*Associate link*。
. 在关联链接页面中，选择*关联现有链接*，选择链接，然后选择*继续*。
. 选择身份验证模式。
+
** Workload Factory：输入密码两次。
** AWS机密管理器：输入机密ARN。
+
机密ARN必须包含以下密钥有效对：

+
*** filesystemID = FSx文件系统ID
*** 用户名 = FSx_user
*** 密码= USER_password




. 选择 * 应用 * 。


.结果
此链接与FSx for ONTAP文件系统关联。您可以执行高级ONTAP操作。



== 对AWS的"Links Manager"链接身份验证问题进行故障排除

问题描述:: 此链接缺少检索密钥的权限。
+
--
*resolution*：链接处于活动状态后添加权限。登录到AWS控制台、找到Lamb代 链接、然后编辑附加的权限策略。

--
问题描述:: 未找到密钥。
+
--
*分辨率*：提供正确的密钥ARN。

--
问题描述:: 机密格式不正确。
+
--
*分辨率*：转到AWS的"27.0"选项并编辑格式。

此密钥应包含以下有效密钥对：

* filesystemID = FSx文件系统ID
* 用户名 = FSx_user
* 密码= USER_password


--
问题描述:: 此密钥不包含用于文件系统身份验证的有效ONTAP凭据。
+
--
*解决方案*：提供可在AWS密码管理器中对ONTAP文件系统FSx进行身份验证的凭据。

--

