---
sidebar: sidebar 
permalink: create-volume.html 
keywords: create volume, FSx for ONTAP volume 
summary: 设置 FSx for ONTAP 文件系统后，在工作负载工厂中创建 FSx for ONTAP 卷。 
---
= 在工作负载工厂中创建 FSx for ONTAP 卷
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
设置 FSx for ONTAP 文件系统后，在工作负载工厂中创建 FSx for ONTAP 卷作为用于对数据进行分组的虚拟资源。

.关于此任务
FSx for ONTAP 卷以虚拟方式对数据进行分组，确定数据的存储方式，并确定对数据的访问类型。卷不会占用文件系统存储容量。存储在卷中的数据主要占用SSD存储。根据卷的分层策略、数据可能还会占用容量池存储。您可以在创建卷时设置其大小、并可稍后更改其大小。

卷可能会使用以下协议：

* CIFS：适用于Windows操作系统的文件存储协议
* NFS：适用于Unix操作系统的文件存储协议
* iSCSI：块存储协议


.开始之前
创建卷之前、请查看以下前提条件：

* 工作负载出厂时必须具有FSx for ONTAP文件系统。
* 您必须具有Storage VM。
* 要访问协议、请完成以下操作：
+
** 要配置对卷的访问，您必须关联一个链接。link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["了解如何关联现有链接或创建并关联新链接"](英文)链接关联后、返回此操作。
** 您必须为所选协议(CIFS、NFS或iSCSI)配置访问权限。






== 创建卷

您可以使用CodeBox中提供的以下工具创建卷：REST API、CloudFormation和Terraform。link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox["了解如何使用CodeBox实现自动化"^](英文)


NOTE: 使用来自CodeBox的Terraform时、您复制或下载的代码会隐藏 `fsxadmin` 和 `vsadmin` 密码。运行代码时、您需要重新输入密码。

.步骤
. 使用其中一个登录link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["控制台体验"^]。
. 在存储中，选择*转至存储清单*。
. 在*FSx for ONTAP选项卡中，选择要创建卷的文件系统的三点菜单，然后选择*Create volume*。
. 在Create volume页面上的General Details下、提供以下详细信息：
+
.. *卷名称*：输入卷的名称。
.. * Storage VM名称*：(可选)输入Storage VM名称。
.. *卷样式*：选择* FlexVol *或* FlexGroup *卷。
+
默认情况下、FlexVol卷模式处于选中状态。

+
FlexGroup卷大小取决于成分卷的数量。每个成分卷需要100 GiB。

.. *卷大小*：输入卷大小和单位。
+
(可选)启用卷自动增长。当您选择*文件访问*作为卷访问类型时，此选项可用。

.. 卷自动增长：可选启用卷自动增长功能，自动扩展卷容量，直至达到最大容量。此功能可适应不断增长的数据使用量，确保运行不中断。
+
指定卷的最大增长大小和单位。最大增长大小不能小于当前卷大小。

.. *标记*：您可以选择最多添加50个标记。


. 在"Access"(仅适用于具有关联链接的文件系统)下、提供以下详细信息：
+
.. *访问类型*：选择*文件访问*或*块访问*。用于配置卷访问的其他字段因您的选择而异。
+
*** *文件访问*：允许多个授权用户和设备使用SMB/CCIFS、NFS或双(SMB/NFS)协议访问卷。
+
填写以下字段以设置对卷的文件访问权限。

+
.... *NFS导出策略*：提供以下详细信息以提供NFS访问：
+
..... *访问控制*：从下拉菜单中选择*自定义导出策略*、*现有导出策略*或*无法访问卷*。
..... *导出策略名称*:
+
如果选择了自定义导出策略、请从下拉菜单中选择现有策略名称。

+
如果选择了现有导出策略、请输入新的策略名称。

..... *添加导出策略规则*：对于自定义导出策略、您可以选择向策略中添加导出策略规则。


.... *CIFS共享*：提供以下内容：
+
..... *名称*：输入CIFS共享名称以提供SMB访问。
..... *权限*：选择“完全控制”、“读/写”、“读取”或“无访问权限”，然后输入用户或组，以分号(;)分隔。用户或组区分大小写、必须使用"域\用户名"格式包含用户的域。


.... *安全模式*：对于双协议卷、请选择UNIX或NTFS安全模式。UNIX是双协议卷的默认安全模式。有关此上下文中用户映射的详细指导，请参阅AWS博客文章link:https://aws.amazon.com/blogs/storage/enabling-multiprotocol-workloads-with-amazon-fsx-for-netapp-ontap["使用Amazon FSx for NetApp ONTAP启用多协议工作负载"^]。


*** *块访问*：允许运行关键业务应用程序的主机使用iSCSI协议访问卷。只有当文件系统横向扩展部署包含六个或更少的HA对时、才能使用块访问。
+
填写以下字段以设置对卷的块访问。

+
.... *iSCSI配置*：提供以下详细信息以配置iSCSI以对卷进行块访问。
+
..... 选择*创建新启动程序组*或*映射现有启动程序组*。
..... 从下拉菜单中选择*主机操作系统*。
..... 输入新启动程序组的*启动程序组名称*。
..... 在Host Initiators下、添加一个或多个iSCSI限定名称(iSCSI限定名称、IQN)主机启动程序。








. 在效率和保护下、提供以下详细信息：
+
.. *存储效率*：默认启用。选择此项可禁用该功能。
+
可通过利用ONTAP的重复数据删除和数据压缩功能来实现存储效率。重复数据删除可消除重复的数据块。数据压缩可压缩数据块，以减少所需的物理存储量。

.. *immutable files*：默认情况下、此功能(也称为SnapLock)处于禁用状态。启用不可删除文件可防止在指定时间段内删除或覆盖数据。只有在创建卷期间才能启用此功能。启用此功能后、将无法禁用它。这是FSx for ONTAP的一项高级功能、需要额外付费。有关详细信息、请参阅link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/how-snaplock-works.html["SnapLock的工作原理"^]Amazon FSx for NetApp ONTAP文档中的。
+
启用不可更改文件功能会将此卷中的文件永久提交到不可更改的WORM (一次写入、多次读取)状态。

+
保留模式:: 您可以从两种保留模式中进行选择-_Enterprise或_Compliance。
+
--
*** 在_Enterprise模式(不可更改的文件或SnapLock)下、管理员可以在文件保留期间删除该文件。
*** 在_Compliance模式下、无法在WORM文件的保留期限到期之前将其删除。同样、在卷中所有文件的保留期限到期之前、无法删除不可更改的卷。


--
保留期限:: 保留期限有两项设置-_保留 策略_和_保留 期限_。retri力policy_定义 了文件在不可固定的WORM状态下保留多长时间。您可以指定自己的保留策略或使用默认保留策略(未指定)、即30年。最小值和最大值_保留期限_用于定义允许锁定文件的时间范围。
+
--
注意:: 即使保留期限到期、您也无法修改WORM文件。您只能将其删除或设置新的保留期限以重新启用WORM保护。


--
自动完成:: 您可以选择启用自动提交功能。如果文件在自动提交期限内未发生更改、则自动提交功能会将文件提交到SnapLock卷上的WORM状态。默认情况下、自动提交功能处于禁用状态。要自动提交的文件必须驻留在 SnapLock 卷上。
卷附加模式:: 您不能修改受WORM保护的文件中的现有数据。但是、通过不可改变的文件、您可以使用WORM可附加文件来保护现有数据。例如、您可以生成日志文件或保留音频或视频流数据、同时以增量方式向这些数据写入数据。link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/worm-state.html#worm-state-append["了解有关卷附加模式的更多信息"^]在Amazon FSx for NetApp ONTAP文档中。
+
--
.不可配置文件的步骤
... 选择以启用由SnapLock提供支持的*不可更改文件*。
... 选中相应框以同意并继续。
... 选择 * 启用 * 。
... *保留模式*：选择*企业*或*合规*模式。
... *保留期限*：
+
**** 选择保留策略：
+
***** *未指定*：将保留策略设置为30年。
***** *指定期限*：输入秒数、分钟数、小时数、天数、月数或年数以设置您自己的保留策略。


**** 选择最短和最长保留期限：
+
***** *最小*：输入秒数、分钟数、小时数、天数、月数或年数以设置最短保留期限。
***** *最大*：输入秒数、分钟数、小时数、天数、月数或年数以设置最长保留期限。




... *AutoCommit *：禁用或启用自动提交。如果启用了自动提交、请设置自动提交期限。
... *卷附加模式*：禁用或启用。用于向WORM文件添加新内容。


--


.. *Snapshot policy*：选择快照策略以指定快照的频率和保留时间。
+
以下是AWS的默认策略。对于自定义快照策略，您必须link:link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["关联链接"] 。

+
`default`:: 此策略会按照以下计划自动创建快照、并删除最早的快照副本、以便为较新的副本腾出空间：
+
--
*** 每小时过五分钟创建最多六个每小时快照。
*** 星期一到星期六午夜后10分钟最多创建两个每日快照。
*** 每个星期日午夜后15分钟创建的每周快照数最多为两个。
+

NOTE: 快照时间基于文件系统的时区、默认为协调世界时(UTC)。有关更改时区的信息、请参阅 link:https://library.netapp.com/ecmdocs/ECMP1155684/html/GUID-E26E4C94-DF74-4E31-A6E8-1D2D2287A9A1.html["显示和设置系统时区"^] NetApp支持文档中的。



--
`default-1weekly`:: 此策略的工作方式与此策略相同 `default` 、只是仅保留每周计划中的一个快照。
`none`:: 此策略不会创建任何快照。您可以将此策略分配给卷、以防止自动创建快照。


.. *分层策略*：为卷中存储的数据选择分层策略。
+
使用工作负载出厂控制台创建卷时、默认分层策略为_Balanced (Auto)_。有关卷分层策略的详细信息、请参阅 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["卷存储容量"^] AWS FSx for NetApp ONTAP文档中的。请注意、工作负载工厂在工作负载工厂控制台中使用基于用例的名称来执行分层策略、并将FSx for ONTAP分层策略名称括在圆括号中。



. 在高级配置下、提供以下内容：
+
.. *接合路径*：在Storage VM的命名空间中输入卷的挂载位置。默认接合路径为 `/<volume-name>`。
.. *聚合列表*：仅适用于FlexGroup卷。添加或删除聚合。最小聚合数为1。
.. *成分卷数*：仅适用于FlexGroup卷。输入每个聚合的成分卷数。每个成分卷需要100 GiB。


. 选择 * 创建 * 。


.结果
已启动卷创建。创建后、新卷将显示在"Volumes"(卷)选项卡中。
