---
sidebar: sidebar 
permalink: enable-auto-capacity-management.html 
keywords: auto capacity, automatic capacity management, file system capacity 
summary: 通过启用此功能、工作负载工厂可以在容量需求随时间变化时自动向FSx for ONTAP文件系统添加增量存储。 
---
= 为FSx for ONTAP文件系统启用自动容量管理
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
启用自动容量管理后，BlueXP 工作负载工厂可以根据容量需求随时间变化自动向 FSx for ONTAP 文件系统添加增量存储。此外，启用此功能无需手动监控容量，并降低了影响应用程序数据读写的风险。

.关于此任务
每30分钟对FSx for ONTAP文件系统进行一次扫描、以确定是否需要添加增量存储并检查卷中的可用卷索引节点或最大文件和文件夹数、以便其计数根据配置的自动容量管理阈值增加。

只有一个帐户可以管理此功能。

适用于ONTAP文件系统的所有FSx的最大SSD存储容量为524、288 GiB。要申请增加配额、请参见 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/limits.html["配额"^] AWS FSx for NetApp ONTAP文档中的。

.开始之前
开始之前、请考虑以下事项：

* 您必须拥有工作负载工厂中具有读/写权限的凭据才能完成此任务。
* 为了确保卷 inode 随着存储容量的增加，您必须关联一个链接。link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["了解如何关联现有链接或创建并关联新链接"](英文)链接关联后、返回此操作。
* 您不应在数据迁移期间启用此功能，因为 AWS 规定 SSD 容量增加之间至少需要六小时的冷却期。此限制可能会延迟调整，因此请做好相应的规划。


.步骤
. 使用其中一个登录link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["控制台体验"^]。
. 在存储中，选择*转至存储清单*。
. 在*FSx for FS* ONTAP选项卡中，选择文件系统的三点菜单，为启用自动容量管理。
. 选择 * 管理 * 。
. 在“Information (信息)”下，选择“*Automatic Capacity management (自动容量管理)”旁边的铅笔图标。当鼠标悬停在*Automatic Capacity management *行上时，下拉箭头旁边将显示铅笔图标。
. 在*自动容量管理*对话框中，提供以下内容：
+
.. *凭据*：从下拉菜单中选择具有_Autome_权限的凭据。
.. 选择启用按钮以*启用自动容量管理*。
+
或者、也可以禁用此功能。如果需要增加文件系统容量、则必须先禁用自动容量管理。

.. *阈值增加*：输入FSx for ONTAP文件系统的最大大小。
.. *增量增加*：输入用于增量增加容量的百分比。
.. 可选：启用自动索引节点管理、通过将索引节点(文件)数量增加到允许的限制来确保每个卷的文件容量可以纵向扩展。


. 选择 * 应用 * 。


.结果
每30分钟执行一次文件系统扫描、以确定文件系统是否需要额外容量。
