---
sidebar: sidebar 
permalink: increase-file-system-capacity.html 
keywords: adjust capacity, elastic file system capacity, increase file system capacity, increase FSx capacity, decrease file system capacity, decrease FSx capacity 
summary: 手动调整 FSx for ONTAP文件系统的 SSD 存储容量，以满足具有不同活动工作集的基于项目的工作负载的需求。 
---
= 在工作负载工厂中调整文件系统容量
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
手动调整 FSx for ONTAP文件系统的固态硬盘 (SSD) 存储容量，以满足具有不同活动工作集的基于项目的工作负载的需求。

当使用的 SSD 存储容量超过您指定的阈值时，增加 FSx for ONTAP文件系统的 SSD 存储容量，或者在工作集不活动时减少 SSD 存储容量，以提高成本效率。

或者、您也可以link:enable-auto-capacity-management.html["启用自动容量管理功能"]让工作负载工厂为您管理文件系统容量。

.关于此任务
利用弹性文件系统容量，您可以动态调整文件系统的容量以满足工作负载的需求。

调整文件系统容量会影响 FSx for ONTAP文件系统的 IOPS。

当你自动link:provision-iops.html["配置IOPS"]对于文件系统，SSD 容量每增加或减少 1 GiB，IOPS 就会增加或减少 3 IOPS。

手动时link:provision-iops.html["配置IOPS"]、您可能需要增加IOPS分配以支持增加的文件系统容量。

有关SSD存储容量限制、请参阅 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/limits.html["配额"^] AWS FSx for NetApp ONTAP文档中的。

.开始之前
要调整文件系统的容量，必须先link:enable-auto-capacity-management.html["禁用自动容量管理"]。

.步骤
. 使用其中一个登录link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["控制台体验"^]。
. 在存储中，选择*转至存储清单*。
. 从仪表板中选择*调整 SSD 容量*。
. 选择您要调整容量的文件系统，然后选择*继续*。
+
*潜在节省*是减少容量的建议。

. 在调整 SSD 容量对话框中，输入 *预配置容量* 的数字。
. 选择已配置容量的单位。
. 选择 * 应用 * 。

