---
sidebar: sidebar 
permalink: known-limitations.html 
keywords: limitations, fsx, ontap 
summary: 已知限制确定了本产品版本不支持的平台、设备或功能、或者这些平台、设备或功能无法与产品正确交互操作。 
---
= Amazon FSx for NetApp ONTAP的已知限制
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
已知限制确定了本产品版本不支持的平台、设备或功能、或者这些平台、设备或功能无法与产品正确交互操作。仔细审查这些限制。



== 高级ONTAP操作需要链接

要在工作负载出厂用户界面中完成某些操作(如复制)、需要使用链接。



== 吞吐量容量区域支持



=== 纵向扩展部署

以下地区支持纵向扩展部署的最大吞吐量高达4 GB/秒：美国东部(俄亥俄州)地区、美国东部(弗吉尼亚)地区、美国西部(俄勒冈)地区和欧洲(爱尔兰)。



=== 横向扩展部署

以下地区支持的横向扩展部署最大吞吐量为3和6 GB/秒：美国东部(北弗吉尼亚)、美国东部(俄亥俄州)、美国西部(俄勒冈)、欧洲(爱尔兰)和亚太地区(悉尼)。



== 容量管理

* iSCSI协议当前不支持卷自动增长功能。
* 运行自动容量管理功能时、不允许手动增加容量。
* 只有使用与启用自动容量管理功能相同的权限、才能禁用该功能。




== Storage VM

每个SKU的Storage VM数量是有限的。工作负载工厂不支持创建超出限制的Storage VM。^1^

有关每个文件系统的最大SVM数量、请参见 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-svms.html#max-svms["管理FSx for ONTAP Storage Virtual Machine"^] AWS文档中的。



== iSCSI协议支持

* iSCSI协议仅适用于FlexVol卷。^1^
* 每个卷只能配置一个LUN。




== 区域支持

* 目前不支持加拿大西部(卡尔加里)地区。




== 数据保护

* 无法删除快照。
* 仅支持在FSx for ONTAP文件系统之间进行复制。
* 复制文件系统时、文件系统中的所有卷都会使用相同的复制策略。
* 只有最后一个快照可供还原。




== 存储节省计算器

存储节省计算器不会计算以下配置的成本节省：

* FSx for Windows文件服务器：HDD存储类型
* 弹性块存储(EBS)：ST1、SC1和标准卷类型
* 弹性文件系统(EFS)：突发吞吐量模式




== System Manager

System Manager不支持FSx for ONTAP连接的链接。

注意：

. 适用于Amazon FSx for NetApp ONTAP

