---
sidebar: sidebar 
permalink: known-limitations.html 
keywords: limitations, fsx, ontap 
summary: 已知限制确定了本产品版本不支持的平台、设备或功能、或者这些平台、设备或功能无法与产品正确交互操作。 
---
= Amazon FSx for NetApp ONTAP的已知限制
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
已知限制确定了本产品版本不支持的平台、设备或功能、或者这些平台、设备或功能无法与产品正确交互操作。仔细审查这些限制。



== 区域支持

以下 AWS 区域不受支持：

* 中国地区
* GovCloud（美国）区域
* 秘密云
* 绝密云




== 正在添加HA对限制

* 此操作可能需要大约30分钟才能完成。
* 添加HA对会限制以下操作：添加更多HA对、配置IOPS、增加SSD容量和更新吞吐量容量。




== 吞吐量容量区域支持



=== 纵向扩展部署

在所有地区、纵向扩展配置最高支持2 Gb/秒。以下地区支持纵向扩展部署的最大吞吐量高达4 GB/秒：美国东部(俄亥俄州)地区、美国东部(弗吉尼亚)地区、美国西部(俄勒冈)地区和欧洲(爱尔兰)。



=== 横向扩展部署

以下区域支持高达 6 GB/s 的最大吞吐容量，以进行横向扩展部署：美国东部（弗吉尼亚北部和俄亥俄）、美国西部（加利福尼亚北部和俄勒冈）、欧洲（法兰克福、爱尔兰和斯德哥尔摩）以及亚太地区（新加坡和悉尼）。



== 容量管理

* iSCSI协议当前不支持卷自动增长功能。
* 运行自动容量管理功能时、不允许手动增加容量。
* 只有使用与启用自动容量管理功能相同的权限、才能禁用该功能。
* 当启用自动容量管理时，需要一个链接来确保卷 inode 随着存储容量一起增加。




== Storage VM

每个 SKU 的存储虚拟机数量是有限的。  Workload Factory 不支持创建超出限制的存储虚拟机。^1^

有关每个文件系统的最大SVM数量、请参见 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-svms.html#max-svms["管理FSx for ONTAP Storage Virtual Machine"^] AWS文档中的。



== iSCSI协议支持

* iSCSI协议仅适用于FlexVol卷。^1^
* 每个卷只能配置一个LUN。
* iSCSI 卷不支持减小卷大小。




== 数据保护

* 无法删除快照。
* 复制文件系统时、文件系统中的所有卷都会使用相同的复制策略。
* 对于长期保留复制关系、只有最后一个快照可供还原。
* 不可变更快照不支持以下功能：
+
** 一致性组
** FabricPool
** FlexCache 卷
** SMTape
** SnapMirror活动同步
** 使用-Schedule参数的SnapMirror策略规则
** SnapMirror同步
** SVM数据移动性(用于将SVM从源集群迁移或重新定位到目标集群)






== 存储节省计算器

存储节省计算器不会计算以下配置的成本节省：

* FSx for Windows文件服务器：HDD存储类型
* 弹性块存储(EBS)：ST1、SC1和标准卷类型
* 弹性文件系统(EFS)：突发吞吐量模式




== System Manager

System Manager不支持FSx for ONTAP连接的链接。



== AWS支持

使用控制台代理时不支持 AWS Secrets Manager。



== Amazon S3 访问点限制

每个存储虚拟机的 S3 访问点数量上限为 4,000 个。

注意：

. 适用于Amazon FSx for NetApp ONTAP

