---
sidebar: sidebar 
permalink: learn-fsx-ontap.html 
keywords: Amazon FSx for NetApp ONTAP, FSx, storage, aws 
summary: Amazon FSx for NetApp ONTAP是一项完全托管的服务，允许客户启动和运行文件系统作为 Workload Factory 内工作负载的存储后端。 
---
= 了解NetApp Workload Factory 中的Amazon FSx for NetApp ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Amazon FSx for NetApp ONTAP是一种完全托管的基于云的数据存储服务，可提供高级数据管理功能和高度可扩展的性能。  FSx for ONTAP允许您创建和管理文件系统作为NetApp Workload Factory 中所有工作负载的存储后端。

FSX for ONTAP 提供了与 NetApp 客户目前在内部使用的相同的特性，性能和管理功能，并具有原生 AWS 服务的精简性，灵活性，安全性和可扩展性。

FSx for ONTAP是 Workload Factory 中的_存储_组件。



== 功能

FSx for ONTAP提供以下功能：

* *完全托管服务*：提供与 Workload Factory 控制台集成的完全托管服务。
* *高可用性*：为每个FSx for ONTAP文件系统提供高可用性、支持单可用性区域和多可用性区域部署。
* *自动快照*：通过高效的自动快照保护数据，快照几乎是文件系统或卷的即时、节省空间的时间点只读副本。
* *卷复制*：通过跨Amazon Web Services跨区域复制提供灾难恢复。
* *高效备份*：在紧急情况下、通过另一个区域的数据副本增加额外的保护层。
* *快速克隆*：通过快速克隆加快应用程序开发速度。
* *多协议支持*：支持网络文件系统(NFS)、服务器消息块(SMB)和Internet小型计算机系统接口(iSCSI)协议。
* *高吞吐量*：提供高吞吐量性能、以确保在FSx for ONTAP文件系统上运行的工作负载实现低的低迟发性。
* *内存缓存和NVMe缓存*：包括唯一的内存缓存和NVMe缓存、可提高经常访问的数据的性能。
* *数十万IOP*：利用SSD磁盘提供数十万次IOPS、确保您的存储和工作负载及时获得结果。
* *精简配置*：允许提前配置容量、节省成本、直到需要更多容量为止。
* *重复数据删除和数据压缩*：删除重复数据并对数据进行压缩、以减少FSx for ONTAP文件系统所需的物理存储量、从而节省成本。
* *数据分层*：通过将不常访问的数据从高性能主SSD存储层移至二级容量池存储层、降低存储成本。




== 工作负载工厂的附加功能

* *存储成本比较计算器*：将您的Amazon Elelic Block Store (EBS)、Elelic File System (EFS)和FSx for Windows File Server存储成本与FSx for ONTAP进行比较。通过计算器、您可以查看FSx for ONTAP存储配置如何提供潜在的节省、并计划迁移到FSx for ONTAP存储。
* *Workload Factory用户界面*:提供_Quick cree_和_Advanced cree_部署模式选项。Quick create包含适用于您的存储配置的AWS、NetApp和行业标准最佳实践。
* *Codebox*：为开发人员提供FSx for ONTAP操作的代码查看器、用于复制和下载的代码模板以及用于代码重复使用的自动化目录。




== 使用NetApp Workload Factory 的工具

您可以将NetApp Workload Factory 与以下工具一起使用：

* *Workload Factory 控制台*：Workload Factory 控制台提供您的应用程序和项目的可视化、整体视图。
* * NetApp控制台*： NetApp控制台提供混合界面体验，以便您可以将 Workload Factory 与其他NetApp数据服务一起使用。
* *问我*：使用问我 AI 助手来提问并了解有关 Workload Factory 的更多信息，而无需离开 Workload Factory 控制台。从 Workload Factory 帮助菜单访问“问我”。
* *CloudShell CLI*：Workload Factory 包含一个 CloudShell CLI，可通过基于浏览器的单个 CLI 跨账户管理和操作 AWS 和NetApp环境。从 Workload Factory 控制台顶部栏访问 CloudShell。
* *REST API*：使用 Workload Factory REST API 部署和管理您的 FSx for ONTAP文件系统和其他 AWS 资源。
* *CloudFormation*：使用 AWS CloudFormation 代码执行您在 Workload Factory 控制台中定义的操作，以从您的 AWS 账户中的 CloudFormation 堆栈对 AWS 和第三方资源进行建模、配置和管理。
* *Terraform NetApp Workload Factory 提供商*：使用 Terraform 构建和管理在 Workload Factory 控制台中生成的基础架构工作流。




== 成本

AWS 维护您的 FSx for ONTAP帐户，而不是 Workload Factory。请参阅link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html#pricing-for-fsx-ontap["Amazon FSx for NetApp ONTAP的定价"^] 。



== 区域

所有支持 FSx for ONTAP 的商业区域都支持工作负载工厂。link:https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["查看支持的 Amazon 地区。"^]

以下 AWS 区域不受支持：

* 中国地区
* GovCloud（美国）区域
* 秘密云
* 绝密云




== 获取帮助

适用于NetApp ONTAP 的Amazon FSX是AWS第一方解决方案。如有与您的FSx for ONTAP文件系统、基础架构或使用此服务的任何解决方案相关的问题或技术支持问题、请使用AWS管理控制台中的支持中心创建AWS支持案例。选择 "FSX for ONTAP " 服务和相应的类别。提供创建 AWS 支持案例所需的其余信息。

有关 Workload Factory 或 Workload Factory 应用程序和服务的一般问题，请参阅link:get-help.html["获取有关 FSx for ONTAP for Workload Factory 的帮助"]。
