---
sidebar: sidebar 
permalink: links-overview.html 
keywords: links, accounts, lambda 
summary: Workload Factory 链接在 Workload Factory 帐户和一个或多个 FSx for ONTAP文件系统之间创建信任关系和连接。 
---
= 了解有关NetApp Workload Factory 链接的信息
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory 链接在 Workload Factory 帐户和一个或多个 FSx for ONTAP文件系统之间创建信任关系和连接。这使您可以直接从ONTAP REST API 调用监控和管理某些文件系统功能，而这些功能无法通过Amazon FSx for ONTAP API 获得。

您不需要链接即可开始使用 Workload Factory，但在某些情况下，您需要创建链接来解锁所有 Workload Factory 功能和工作负载能力。



== 为什么链接是有益的

链接很有用，因为它们允许 Workload Factory 执行通过Amazon FSx for ONTAP API 本身无法执行的操作。链接支持高级ONTAP功能和自动化，从而增强 FSx for ONTAP文件系统的管理。

以下是使用链接的一些好处：

* 该链接使NetApp控制台能够将ONTAP命令直接发送到您的 FSx for ONTAP文件系统，从而带来 AWS 原生提供的ONTAP高级功能。
* 链接利用 AWS Lambda 执行代码来响应事件。这种无服务器方法消除了对 VPC 中运行实例的依赖。




== 链接的工作原理

链路利用AWS Lambs。在事件发生后、兰代执行代码、并自动管理该代码所需的计算资源。您创建的链接属于您的NetApp帐户、它们与AWS帐户相关联。

创建链接后，您可以将其与一个或多个 FSx for ONTAP文件系统关联。每个文件系统只能与同一个NetApp帐户中的一个链接相关联。如果您有多个NetApp帐户、则一个文件系统可以与不同NetApp帐户下的其他链接相关联。

您可以在工作负载工厂中创建并关联来自存储工作负载的链接。

您可以使用存储在 Workload Factory 凭证服务中的凭证或存储在 AWS Secrets Manager 中的凭证来验证链接。工作负载工厂不支持更改身份验证模式。



== Costs

Lambda 执行的每笔交易都会产生费用。由于 Lambda 充当两个系统之间的代理，因此当 Lambda 向文件系统上的ONTAP REST API 发送请求时以及将响应发送回 Workload Factory 时都会产生费用。

link:https://aws.amazon.com/lambda/pricing/["详细了解与使用AWS Lamb泄 压相关的成本"^]



== 需要链接时

工作负载工厂需要一个链接来显示一些信息并执行一些任务。如果您尝试执行需要链接的操作，但尚未将链接与 FSx for ONTAP文件系统关联，则 Workload Factory 会通知您该操作需要链接。

需要链接的功能包括：

* FSx for ONTAP文件系统配置的良好架构状态，可实现主动维护、可靠性和成本效益优化
* NetApp自主勒索软件防护 (ARP/AI)
* 增强了 FSx for ONTAP文件系统的整体容量可观察性
* 卷和存储虚拟机数据复制、管理和监控
* SMB/CIFS 共享和 NFS 导出策略配置和管理
* 在FSx for ONTAP文件系统上管理iSCSI卷
* 创建和管理自定义保护 SLA 的快照策略
* 增强 Inode 管理以实现自动容量管理
* 容量自动增长以实现弹性扩展
* 克隆创建和管理，用于即时、就地数据克隆
* 直接从ONTAP显示其他指标，例如ONTAP版本


了解如何link:create-link.html["将链接连接到 FSx for ONTAP文件系统"]。
