---
sidebar: sidebar 
permalink: manage-snapshot-policy.html 
keywords: manage snapshot policy, change snapshot policy, snapshot policies, snapshot schedule, update 
summary: 在工作负载工厂中管理 FSx for ONTAP 卷的快照策略。快照策略用于定义系统如何为卷创建快照。 
---
= 管理Snapshot策略
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
在工作负载工厂中管理 FSx for ONTAP 卷的快照策略。快照策略用于定义系统如何为卷创建快照。

.关于此任务
为FSx for ONTAP文件系统中的卷分配、更改和删除Snapshot策略等Snapshot管理操作在Storage VM级别进行管理。Snapshot策略可以与单个Storage VM共享、也可以与所有Storage VM共享。

某些管理任务要求您将链接与 FSx for ONTAP 文件系统关联。link:https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["了解工作负载工厂链接"](英文)

默认情况下、每个卷都与文件系统的快照策略相关联 `default` 。建议对大多数工作负载使用此策略。



== 更改快照策略

您可以更改要保留的快照策略名称、计划和副本数、以及启用或禁用不可变快照。无法在Storage VM之间启用或禁用策略共享。此选项仅在创建Snapshot策略期间可用。

.开始之前
要显示现有的快照策略，您必须关联一个链接。link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["了解如何关联现有链接或创建并关联新链接"](英文)链接关联后、返回此操作。

.步骤
. 使用其中一个登录link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["控制台体验"^]。
. 在*存储*中，选择*转至存储清单*。
. 在*FSx for FS* ONTAP选项卡中，选择文件系统的三点菜单，然后选择*Manage*。
. 在文件系统概述中，选择*Storage VMS*选项卡。
. 从*Storage VM*选项卡中，选择包含要使用计划快照保护的卷的Storage VM的三点菜单，然后选择*Advanced Actions*和*Manage Snapshot Policies*。
. 在Snapshot策略管理页面上，选择要更改的快照策略的三点菜单，然后选择*Edit*。
. 在编辑快照策略对话框中、对快照策略进行必要的更改。
. 选择 * 应用 * 。


.结果
此时将更新此Snapshot策略。



== 启用不可变更的快照

锁定快照、防止在保留期间将其删除。

.开始之前
您必须关联一个链接才能启用不可变快照。link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["了解如何关联现有链接或创建并关联新链接"](英文)链接关联后、返回此操作。

.步骤
. 使用其中一个登录link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["控制台体验"^]。
. 在*存储*中，选择*转至存储清单*。
. 在*FSx for ONTAP SnapMirror*选项卡中，选择包含要锁定快照的卷的文件系统的三点菜单，然后选择*Manage*。
. 在文件系统概述中，选择*Volumes*选项卡。
. 从*卷*选项卡中，选择要保护的卷的三点菜单。
. 选择*数据保护操作*、*快照*，然后选择*使快照不可更改*。
. 在Make a Snapshot immutable对话框中、执行以下操作：
+
.. *Snapshot name*:选择要锁定的快照。
.. 以小时、天、月或年为单位设置*保留期限*。
.. 接受陈述。


. 选择 * 应用 * 。


.结果
卷快照现已锁定。



== 将快照策略分配给卷

您可以将快照策略分配给单个卷、以便为该卷创建计划快照。

.开始之前
您必须关联一个链接才能分配快照策略。link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["了解如何关联现有链接或创建并关联新链接"](英文)链接关联后、返回此操作。

.步骤
. 使用其中一个登录link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["控制台体验"^]。
. 在*存储*中，选择*转至存储清单*。
. 在*FSx for ONTAP选项卡中，选择要将快照策略分配到的卷所在文件系统的三点菜单，然后选择*Manage*。
. 在文件系统概述中，选择*Storage VMS*选项卡。
. 从*Storage VM*选项卡中，选择包含要使用计划快照保护的卷的Storage VM的三点菜单，然后选择*Advanced Actions*和*Manage Snapshot Policies*。
. 在Snapshot策略管理页面上、选择快照策略的三点菜单、然后选择*将策略分配给卷*。
. 在分配快照策略对话框中、选择要分配给卷的快照策略并查看策略计划。
+
如果此策略包含不可更改的快照、并且您希望使用此策略、请接受此语句。

. 选择*Assign*。


.结果
此时将为卷分配Snapshot策略。



== 从卷中删除Snapshot策略

从卷中删除快照策略、因为您不再需要此卷的快照、或者您要删除分配给多个卷的快照策略。对于<<删除快照策略,删除Snapshot策略>>已分配给多个卷的、您必须手动将其从所有卷中删除。

.开始之前
您必须关联一个链接才能删除快照策略。link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["了解如何关联现有链接或创建并关联新链接"](英文)链接关联后、返回此操作。

.步骤
. 使用其中一个登录link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["控制台体验"^]。
. 在*存储*中，选择*转至存储清单*。
. 在*FSx for ONTAP选项卡中，选择要将快照策略分配到的卷所在文件系统的三点菜单，然后选择*Manage*。
. 在文件系统概述中，选择*Storage VMS*选项卡。
. 从*Storage VM*选项卡中，选择包含要使用计划快照保护的卷的Storage VM的三点菜单，然后选择*Advanced Actions*和*Manage Snapshot Policies*。
. 在Snapshot策略管理页面上、选择快照策略的三点菜单、然后选择*将策略分配给卷*。
. 在"Assign Snapshot policy"(分配快照策略)对话框中，选择*None*(无)以删除快照策略。
. 选择*Assign*。


.结果
此时将从卷中删除此Snapshot策略。



== 删除快照策略

删除不再需要的快照策略。

如果将一个快照策略分配给多个卷、则必须从所有卷中手动<<从卷中删除Snapshot策略,将其删除>>删除该快照策略。或者、也可以<<将快照策略分配给卷,分配其他Snapshot策略>>访问卷。

.步骤
. 使用其中一个登录link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["控制台体验"^]。
. 在*存储*中，选择*转至存储清单*。
. 在*FSx for ONTAP选项卡中，选择包含卷的文件系统的三点菜单，然后选择*Manage*。
. 在文件系统概述中，选择*Storage VMS*选项卡。
. 从*Storage VM*选项卡中，选择要删除快照策略的Storage VM的三点菜单，然后选择*Advanced Actions*和*Manage Snapshot Policies*。
. 在Snapshot策略管理页面上，选择要删除的快照策略的三点菜单，然后选择*Delete*。
. 在删除对话框中，选择*Delete*以删除策略。


.结果
此时将删除此Snapshot策略。
