---
sidebar: sidebar 
permalink: pause-resume-replication.html 
keywords: pause replication, quiesce replication, resume replication 
summary: 暂停和恢复复制关系、以便目标卷成为源卷。 
---
= 在BlueXP  工作负载出厂时暂停和恢复复制关系
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
暂停复制关系以停止从源卷到目标卷的计划复制更新。目标卷从只读过渡到读/写。这两个卷仍会共享最新的复制快照作为新基线、以供日后重新同步时使用。

.关于此任务
暂停后、源卷和目标卷之间的复制关系将继续存在。数据传输将暂停、卷将变得独立。要重新启用从源卷到目标卷的更改传输、请恢复复制。

恢复复制后、对目标卷所做的所有更改都将撤消、BlueXP  工作负载出厂时会重新启用复制。目标卷从读/写转换为只读，并再次按照计划的复制间隔从源卷接收更新。恢复复制关系后、目标卷将还原到最新的初始复制快照、此时、卷复制过程将重新开始。

.开始之前
如果在传输进行中暂停、则传输不会受到影响、关系将变为"暂停"、直到传输完成为止。如果当前传输已被禁止、则它现在是将来的传输、不会重新启动。



== 暂停复制关系

.步骤
. 使用其中一个登录link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["控制台体验"^]。
. 在存储中，选择*转至存储清单*。
. 在*FSx for FS* ONTAP选项卡中，选择要更新的文件系统的三点菜单，然后选择*Manage*。
. 从文件系统概述中，选择*复制关系*选项卡。
. 在复制关系选项卡中、选择要暂停的复制关系的三点菜单。
. 选择*暂停(暂停)*。
. 在“*置于两国间的关系”对话框中，选择“*置于两国间的关系”。


.结果
此关系将暂停、并且其状态显示为"Paused"。



== 恢复已暂停的复制关系

恢复复制关系后、在复制停止期间对目标卷所做的任何更改都将被删除。


NOTE: 系统不会保留从上次数据复制到源卷被禁用这段时间写入原始源卷的任何数据。

.步骤
. 使用其中一个登录link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["控制台体验"^]。
. 在存储中，选择*转至存储清单*。
. 在*FSx for FS* ONTAP选项卡中，选择要更新的文件系统的三点菜单，然后选择*Manage*。
. 从文件系统概述中，选择*复制关系*选项卡。
. 在复制关系选项卡中、选择要恢复的复制关系的三点菜单。
. 选择*恢复*。
. 在“恢复关系”对话框中，选择*Resume*。


.结果
此关系将恢复、并且其状态显示为"已复制"。
