---
settings:
  name: Amazon FSx for NetApp ONTAP
  internal:
    pdf_enabled: true
    termcheck_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: zh-cn,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-tw
sidebar:
  entries:
  - title: 适用于NetApp的Amazon FSX ONTAP 文档
    url: "/index.html"
  - title: 发行说明
    entries:
    - title: 新增功能
      url: "/whats-new.html"
    - title: 已知限制
      url: "/known-limitations.html"
  - title: 开始使用
    entries:
    - title: 了解适用于NetApp ONTAP 的Amazon FSX
      url: "/learn-fsx-ontap.html"
    - title: 快速入门
      url: "/quick-start.html"
    - title: 创建FSx for ONTAP文件系统
      url: "/create-file-system.html"
  - title: 使用适用于NetApp ONTAP 的Amazon FSx
    entries:
    - title: 了解节省量
      url: "/explore-savings.html"
    - title: 跟踪和分析 FSx for ONTAP成本
      url: "/track-costs.html"
    - title: 使用链接
      entries:
      - title: 了解链接
        url: "/links-overview.html"
      - title: 使用链接连接到文件系统
        url: "/create-link.html"
      - title: 管理链接
        url: "/manage-links.html"
    - title: 发现并查看缓存卷
      url: "/discover-cache-volumes.html"
    - title: 管理卷
      entries:
      - title: 创建卷
        url: "/create-volume.html"
      - title: 访问您的数据
        url: "/access-data.html"
    - title: 创建Storage VM
      url: "/create-storage-vm.html"
    - title: 保护您的数据
      entries:
      - title: 数据保护概述
        url: "/data-protection-overview.html"
      - title: 使用快照
        entries:
        - title: 创建快照
          url: "/create-snapshot.html"
        - title: 创建快照策略
          url: "/create-snapshot-policy.html"
        - title: 从快照还原卷
          url: "/restore-volume-from-snapshot.html"
      - title: 使用备份到对象存储
        entries:
        - title: 创建手动备份
          url: "/create-backup.html"
        - title: 从备份还原卷
          url: "/restore-from-backup.html"
      - title: 使用复制
        entries:
        - title: 创建复制关系
          url: "/create-replication.html"
        - title: 初始化复制关系
          url: "/initialize-replication.html"
      - title: 利用自主防兰森保护功能保护数据
        url: "/ransomware-protection.html"
      - title: 克隆卷
        url: "/clone-volume.html"
      - title: 使用内部ONTAP数据
        url: "/use-onprem-data.html"
      - title: 创建网络保险库以保护数据
        url: "/create-cyber-vault.html"
  - title: 管理和监控
    entries:
    - title: 使用Tracker监控操作
      url: "/monitor-operations.html"
    - title: 实施文件系统最佳实践
      entries:
      - title: FSx for ONTAP的配置分析
        url: "/configuration-analysis.html"
      - title: 实施架构良好的文件系统配置
        url: "/improve-configurations.html"
    - title: 分析 FSx 中的ONTAP EMS 事件
      url: "/analyze-events.html"
    - title: 卷管理
      entries:
      - title: 编辑卷自动增长
        url: "/edit-volume-autogrow.html"
      - title: 调整音量容量
        url: "/adjust-volume-capacity.html"
      - title: 重新平衡卷容量
        url: "/rebalance-volume.html"
      - title: 管理不可配置文件
        url: "/manage-immutable-files.html"
      - title: 管理卷标记
        url: "/manage-volume-tags.html"
      - title: 管理缓存卷
        url: "/manage-cache-volumes.html"
      - title: 更改层策略
        url: "/change-tiering-policy.html"
      - title: 更新存储效率
        url: "/update-storage-efficiency.html"
      - title: 管理 NFS 导出策略
        url: "/manage-nfs-export-policy.html"
      - title: 管理 SMB/CIFS 共享
        url: "/manage-cifs-share.html"
      - title: 拆分克隆的卷
        url: "/split-cloned-volume.html"
      - title: 删除卷
        url: "/delete-volume.html"
    - title: 块设备管理
      entries:
      - title: 管理块设备
        url: "/manage-block-devices.html"
    - title: 文件系统管理
      entries:
      - title: 调整文件系统容量
        url: "/increase-file-system-capacity.html"
      - title: 启用自动容量和 inode 管理
        url: "/enable-auto-capacity-management.html"
      - title: 管理文件系统标签
        url: "/manage-fsx-tags.html"
      - title: 重置fsxadmin密码
        url: "/reset-fsxadmin-password.html"
      - title: 删除文件系统
        url: "/delete-file-system.html"
    - title: Storage VM 管理
      entries:
      - title: 将Storage VM复制到另一个文件系统
        url: "/replicate-svm-to-file-system.html"
      - title: 配置和更新Storage VM的Active Directory
        url: "/configure-active-directory.html"
      - title: 管理Storage VM标记
        url: "/manage-svm-tags.html"
      - title: 重置Storage VM密码
        url: "/reset-svm-password.html"
      - title: 删除Storage VM
        url: "/delete-svm.html"
    - title: 数据保护管理
      entries:
      - title: 快照
        entries:
        - title: 管理Snapshot策略
          url: "/manage-snapshot-policy.html"
        - title: 启用和编辑快照以进行长期保留
          url: "/enable-snapshots-long-term.html"
        - title: 管理快照
          url: "/manage-snapshots.html"
      - title: 备份
        entries:
        - title: 管理FSx for ONTAP备份计划
          url: "/manage-backup-schedule.html"
      - title: 复制
        entries:
        - title: 复制数据保护卷
          url: "/cascade-replication.html"
        - title: 反转复制关系
          url: "/reverse-replication.html"
        - title: 更改源卷的复制计划
          url: "/change-replication-schedule.html"
        - title: 限制复制关系的最大传输速率
          url: "/limit-transfer-rate.html"
        - title: 手动更新复制关系中的快照数据
          url: "/update-snapshot-replication.html"
        - title: 暂停和恢复复制关系
          url: "/pause-resume-replication.html"
        - title: 停止复制关系
          url: "/stop-replication.html"
        - title: 删除复制关系
          url: "/delete-replication.html"
    - title: 性能管理
      entries:
      - title: 为文件系统配置IOPS
        url: "/provision-iops.html"
      - title: 更新文件系统的吞吐量容量
        url: "/update-throughput-capacity.html"
  - title: 参考
    entries:
    - title: FSx for ONTAP的性能
      url: "/performance-reference.html"
    - title: FSx for ONTAP的安全性
      url: "/security-reference.html"
  - title: 知识和支持
    entries:
    - title: 注册以获得支持
      url: "/support-registration.html"
    - title: 获取帮助
      url: "/get-help.html"
    - title: 故障排除
      url: "/troubleshooting.html"
  - title: 法律声明
    url: "/legal-notices.html"
product-family:
  name: NetApp Workload Factory
  repo: workload-family
