---
sidebar: sidebar 
permalink: rebalance-volume.html 
keywords: rebalance capacity, volume capacity, redistribute capacity 
summary: 检查并重新平衡卷的容量、以避免随着时间的推移而出现不平衡。 
---
= 检查并重新平衡卷的容量
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
检查FlexGroup卷容量的平衡并重新平衡卷容量、以便在所有成分卷之间均匀分布文件、以便所有节点都参与单个Flex Group卷的工作负载。

.关于此任务
FlexGroup卷容量分布在具有两个或更多高可用性(HA)对的适用于ONTAP的横向扩展FSx文件系统中的多个成分卷上。每个成分卷都是一个容器、用于指定单个文件的最大大小。FSx for ONTAP以均匀的方式将文件分布在所有成分卷上、以便所有节点都参与单个FlexGroup卷的工作负载。

如果成分卷未均匀分布在所有节点上、则FlexGroup卷性能会下降。

检查FlexGroup卷容量的平衡情况包括评估成分卷的当前布局。在重新平衡卷的容量时、BlueXP  工作负载工厂会设计一个包含偶数成分卷的新成分卷布局、以便在所有HA对之间均匀分布数据。该服务将执行重新平衡计划、进而改进读取和写入操作。

当由于添加新文件和文件增长而导致逐渐出现不平衡时、重新平衡卷会重新分布容量。手动启动重新平衡操作后、我们会选择文件并自动无中断地移动它们。


NOTE: 只有FlexGroup卷才支持重新平衡卷。



== 检查FlexGroup卷的平衡情况

检查活动FlexGroup卷的平衡情况。

.开始之前
* FlexGroup卷平衡仅适用于使用至少两个HA对的横向扩展部署的适用于ONTAP文件系统的FSx。
* 卷模式必须是FlexGroup卷。
* 要检查FlexGroup卷的平衡情况，您必须link:manage-links.html["关联链接"]。如果您没有现有链接，请 link:create-link.html["创建链接"]。要关联文件系统中的链接，请选择*Account name*下的*Associate link*。链接关联后、返回此操作。


.步骤
. 使用其中一个登录link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["控制台体验"^]。
. 在*存储*中，选择*转至存储清单*。
. 在*FSx for FS* ONTAP选项卡中，选择包含要重新平衡的卷的文件系统的三点菜单，然后选择*Manage*。
. 从文件系统概述中，选择*Volumes*选项卡。
. 从卷选项卡中，选择表顶部的*检查FlexGroup平衡*。
. 在FlexGroup平衡窗口中、查看FSx for ONTAP文件系统中所有FlexGroup卷的平衡状态。
+
如果FlexGroup卷不平衡，请考虑<<重新平衡FlexGroup卷,重新平衡它>>。





== 重新平衡FlexGroup卷

<<检查FlexGroup卷的平衡情况,检查FlexGroup卷的平衡情况>>重新平衡卷之前。

.开始之前
要重新平衡卷，您必须 link:manage-links.html["关联链接"]。如果您没有现有链接，请 link:create-link.html["创建链接"]。要关联文件系统中的链接，请选择*Account name*下的*Associate link*。链接关联后、返回此操作。

.步骤
. 使用其中一个登录link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["控制台体验"^]。
. 在*存储*中，选择*转至存储清单*。
. 在*FSx for FS* ONTAP选项卡中，选择包含要重新平衡的卷的文件系统的三点菜单，然后选择*Manage*。
. 从文件系统概述中，选择*Volumes*选项卡。
. 从卷选项卡中、选择要重新平衡的卷的三点菜单。
. 选择*高级操作*，然后选择*重新平衡卷*。
. 在"Re平衡 卷"对话框中、选择*重新平衡*。


.结果
FlexGroup卷的容量会重新平衡。
