---
sidebar: sidebar 
permalink: rebalance-volume.html 
keywords: rebalance capacity, volume capacity, redistribute capacity 
summary: 检查并重新平衡卷的容量、以避免随着时间的推移而出现不平衡。 
---
= 检查并重新平衡卷的容量
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
检查 FlexVol 或 FlexGroup 卷容量的平衡，并重新平衡卷容量，以将文件均匀分布在节点中的所有 FlexVol 卷或所有组成部分之间，以便所有节点都参与单个 FlexGroup 卷的工作负载。

.关于此任务
FlexVol 卷和 FlexGroup 卷支持重新平衡卷容量。当由于添加新文件和文件增长而导致逐渐出现不平衡时、重新平衡卷会重新分布容量。手动启动重新平衡操作后、我们会选择文件并自动无中断地移动它们。卷传输操作会占用文件系统资源。

每种卷类型和重新平衡操作均有不同，如下所示。

FlexVol 卷:: FlexVol 卷是一种逻辑容器，能够灵活地管理数据，支持扩展、收缩、移动和高效复制。它们适用于 NAS 和 SAN 环境。
+
--
在 FSx for ONTAP 文件系统中，一个 FlexVol 卷可以与一个节点内的其他 FlexVol 卷进行平衡。如果文件系统只有一个 FlexVol 卷，则无法进行重新平衡。当文件系统每个节点有多个 FlexVol 卷并且选择了单个 FlexVol 卷时，该 FlexVol 卷会在所有 FlexVol 卷的上下文中进行平衡，但只允许移动选定的卷。

--
FlexGroup 卷:: 另一方面，FlexGroup 卷是可扩展的 NAS 容器，旨在实现高性能和自动负载分配。它们由多个成员卷（组成部分）组成，这些成员卷透明地共享流量。FlexGroup卷提供海量容量，超越 FlexVol 的限制，最高可达 60PB 容量和 4000 亿个文件。它们通过提供单一命名空间容器来简化管理。
+
--
容量分布在具有两个或更多高可用性 (HA) 对的横向扩展 FSx for ONTAP 文件系统的多个组成部分中。每个成分卷都是一个容器、用于指定单个文件的最大大小。FSx for ONTAP以均匀的方式将文件分布在所有成分卷上、以便所有节点都参与单个FlexGroup卷的工作负载。

如果成分卷未均匀分布在所有节点上、则FlexGroup卷性能会下降。

检查FlexGroup卷容量的平衡情况包括评估成分卷的当前布局。在重新平衡卷的容量时、BlueXP  工作负载工厂会设计一个包含偶数成分卷的新成分卷布局、以便在所有HA对之间均匀分布数据。该服务将执行重新平衡计划、进而改进读取和写入操作。

--



NOTE: iSCSI 和 NVMe 等 SAN 卷不支持重新平衡。



== 检查您的交易量余额

检查 FSx for ONTAP 文件系统中 FlexVol 或 FlexGroup 卷的平衡。

.开始之前
* FlexGroup卷平衡仅适用于使用至少两个HA对的横向扩展部署的适用于ONTAP文件系统的FSx。
* 要检查卷的余额，您必须link:manage-links.html["关联链接"] 。如果您没有现有链接，请 link:create-link.html["创建链接"]。要关联文件系统中的链接，请选择*Account name*下的*Associate link*。链接关联后、返回此操作。


.步骤
. 使用其中一个登录link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["控制台体验"^]。
. 在*存储*中，选择*转至存储清单*。
. 在 *FSx for ONTAP* 选项卡中，选择包含要重新平衡的卷的文件系统的三点菜单，然后选择 *管理*。
. 从文件系统概述中，选择*Volumes*选项卡。
. 从“卷”选项卡中，选择表格顶部的“检查卷余额”。
. 在“交易量平衡”窗口中，查看以下平衡状态：
+
** FlexGroup 卷
** FlexVol 卷
+
当音量不平衡时，请考虑<<重新平衡卷容量,重新平衡它>> 。







== 重新平衡卷容量

重新平衡一个或多个不平衡的卷。


NOTE: 工作负载工厂管理员可以<<停止卷重新平衡操作,停止重新平衡>>在操作过程中。

.开始之前
* <<检查您的交易量余额,检查卷的余额>>重新平衡卷之前。
* 要重新平衡卷，您必须 link:manage-links.html["关联链接"]。如果您没有现有链接，请 link:create-link.html["创建链接"]。要关联文件系统中的链接，请选择*Account name*下的*Associate link*。链接关联后、返回此操作。
* 请注意、要重新平衡的卷上的现有快照会变为部分快照、不能用于还原卷数据、但在重新平衡后创建的新快照可用于还原卷数据。
* 最好将 FlexVol 卷全部重新平衡，以便均匀地平衡所有卷资源。取消选定的卷不会主动参与平衡过程。


[role="tabbed-block"]
====
.FlexVol volume
--
在 FSx for ONTAP 文件系统中，一个 FlexVol 卷可以与同一节点内的其他 FlexVol 卷进行平衡。当文件系统每个节点有多个 FlexVol 卷且选择了单个 FlexVol 卷时，该 FlexVol 卷会在所有 FlexVol 卷的上下文中进行平衡，但只允许移动选定的卷。

.步骤
. 使用其中一个登录link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["控制台体验"^]。
. 在*存储*中，选择*转至存储清单*。
. 在*FSx for FS* ONTAP选项卡中，选择包含要重新平衡的卷的文件系统的三点菜单，然后选择*Manage*。
. 从文件系统概述中，选择*Volumes*选项卡。
. 从“卷”选项卡中，选择表格顶部的“检查卷余额”。
. 在卷平衡窗口中，可以选择 FlexVol 平衡摘要中的“*数据分布*”来查看每个聚合的已用容量。
. 选择“*重新平衡*”以重新平衡一个或多个不平衡的卷。
. 在重新平衡向导中，按照以下步骤操作。
+
.. *最大传输速率*：可选。默认情况下处于禁用状态。启用限制可限制文件系统上卷移动的带宽、并降低传出卷复制流量的速度。
+
以MB/秒为单位输入限制值

+
选择 * 下一步 * 。

.. 查看所有 FlexVol 卷的当前和建议布局，然后选择*下一步*。
.. 在开始重新平衡操作之前，请仔细检查将会发生什么以及注意事项。


. 选择*重新平衡*。


.结果
FlexVol 卷已重新平衡。操作完成后、文件系统将被控制回原始值。

--
.FlexGroup 卷
--
数据在成员卷之间重新分布以重新平衡FlexGroup卷。根据您选择的布局，重新平衡操作可能会添加 FlexGroup 成员卷并增加已配置卷的大小。

.步骤
. 使用其中一个登录link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["控制台体验"^]。
. 在*存储*中，选择*转至存储清单*。
. 在*FSx for FS* ONTAP选项卡中，选择包含要重新平衡的卷的文件系统的三点菜单，然后选择*Manage*。
. 从文件系统概述中，选择*Volumes*选项卡。
. 从卷选项卡中，选择表顶部的*检查FlexGroup平衡*。
. 在FlexGroup平衡窗口中、选择*重新平衡*以重新平衡一个或多个不平衡的卷。
. 在重新平衡向导中、选择您喜欢的数据分布布局。
+
** *性能优化*(建议)：增加FlexGroup成员卷的数量和卷的配置大小。遵循NetApp最佳实践。
** *受限*：支持复制关系中的卷。FlexGroup成员卷的数量和已配置卷的大小保持不变。如果所有选定卷都参与复制关系、则默认选中此选项。
** *手动*：为每个HA对选择所需数量的FlexGroup成员卷。根据您的选择、FlexGroup成员卷的数量和卷的已配置大小可能会增加。


. *Throttling *：可选。默认情况下处于禁用状态。启用限制可限制文件系统上卷移动的带宽、并降低传出卷复制流量的速度。
+
以MB/秒为单位输入限制值

. 选择布局比较视图，然后选择*Next*。
+
** 卷布局比较
** FSx for ONTAP布局比较


. (可选)在重新平衡之前下载卷移动列表。
. 选择*重新平衡*。


.结果
在重新平衡期间，FlexGroup 成员卷一次移动一个。操作完成后、文件系统将被控制回原始值。

--
====


== 停止卷重新平衡操作

随时停止重新平衡操作；这不会造成中断。停止操作会中止正在进行的卷移动。

您可以稍后开始另一个重新平衡操作。

.步骤
. 开始重新平衡操作后，从卷平衡页面选择*停止重新平衡*。
. 在停止重新平衡对话框中，选择*停止*。


.结果
卷重新平衡操作停止并且活动卷移动中止。
