---
sidebar: sidebar 
permalink: replicate-svm-to-file-system.html 
keywords:  
summary: 将Storage VM复制到另一个FSx for ONTAP文件系统可在数据丢失时提供一个数据访问保护层。 
---
= 将Storage VM复制到另一个FSx for ONTAP文件系统
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
将Storage VM复制到另一个FSx for ONTAP文件系统可在数据丢失时提供一个数据访问保护层。此操作会将一个Storage VM中的所有卷复制到另一个FSx for ONTAP文件系统。

.开始之前
要将Storage VM复制到另一个FSx for ONTAP文件系统，您必须 link:manage-links.html["关联链接"]。如果您没有现有链接，请 link:create-link.html["创建链接"]。要关联文件系统中的链接，请单击*Account name*下的*Associate link*。链接关联后、返回此操作。

.步骤
. 登录到 link:https://console.workloads.netapp.com/["工作负载出厂控制台"^]
. 在存储中，选择*转至存储清单*。
. 在*FSx for Storage VM*选项卡中，选择包含要复制的ONTAP的文件系统的三点菜单，然后选择*Manage*。
. 从文件系统概述中，选择*Storage VMS*选项卡。
. 从Storage VM选项卡中、选择要复制SVM的Storage VM的三个点菜单。
. 选择*复本Storage VM*。
. 在创建复制页面上的复制目标下、提供以下内容：
+
.. *FSx for ONTAP file system*：为目标FSx for ONTAP文件系统选择ONTAP文件系统的凭据、区域和FSx名称。
.. * Storage VM名称*：从下拉菜单中选择Storage VM。
.. *卷名*：目标卷名称将自动生成，格式如下 `{OriginalVolumeName}_copy`。
.. *分层策略*：为目标卷中存储的数据选择分层策略。
+
_Auto_是使用工作负载Factory FSx for ONTAP用户界面创建卷时的默认分层策略。有关卷分层策略的详细信息、请参阅 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["卷存储容量"^]AWS FSx for NetApp ONTAP文档中的。

.. *最大传输速率*：选择*受限*并输入最大传输速率(MB/秒)或者，选择*Unlimited (无限制)*。
+
如果没有限制、网络和应用程序性能可能会下降。或者、对于关键工作负载(例如、主要用于灾难恢复的工作负载)、我们建议对用于ONTAP文件系统的FSx使用无限传输速率。



. 在复制设置下、提供以下内容：
+
.. *复制间隔*：选择从源卷向目标卷传输快照的频率。
.. *长期保留*：(可选)启用快照以进行长期保留。
+
如果启用长期保留、请选择现有策略或创建新策略以定义要复制的快照以及要保留的数量。

+
... 对于*Choose an existing policy*，从下拉菜单中选择一个现有策略。
... 对于*Create a new policy*，请提供以下内容：
+
.... *策略名称*：输入策略名称。
.... *Snapshot策略*：在表中，选择快照策略频率和要保留的副本数。您可以选择多个快照策略。






. 单击 * 创建 * 。


.结果
Storage VM中的所有卷都会复制到目标文件系统。
