---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, workload factory, amazon fsx for netapp ontap, fsx for ontap' 
summary: 了解Amazon FSx for NetApp ONTAP的新增功能。 
---
= 新增功能
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
了解Amazon FSx for NetApp ONTAP的新增功能。



== 2024年11月3日



=== 存储清单中的选项卡视图

存储清单已更新为双选项卡视图：

* FSx for ONTAP选项卡：显示您当前拥有的适用于ONTAP文件系统的FSx。
* Explore savings选项卡：显示Elabic Block Store、FSx for Windows File Server和Elabic File Systems存储系统。然后、您可以通过将这些系统与FSx for ONTAP进行比较来了解节省的空间。




== 2024年9月29日



=== 更新链接创建

* CodeBox查看器：CodeBox现在集成在链接创建过程中。您可以在重定向到AWS以执行此操作之前从Workload Factory中的CodeBox查看和复制CloudFormation模板。
* 所需权限：现在、您可以在工作负载工厂的创建链接向导中查看和复制在AWS CloudFormation中创建链接所需的权限。
* 支持手动创建链接：此功能允许通过手动注册链接ARN在AWS CloudFormation中独立创建。当安全或开发运营团队协助创建链接时、这将非常有用。


link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["创建链接"^]



== 2024年9月1日



=== 为存储管理提供读取模式支持

在Workload Factory中、可以使用读取模式进行存储管理。读取模式通过添加只读权限来增强基本模式的体验、以便在基础架构即代码模板中填充特定变量。基础架构即代码模板可以直接从AWS帐户执行、而无需向Workload Factory提供任何修改权限。

link:https://docs.netapp.com/us-en/workload-setup-admin/operational-modes.html["了解有关读取模式的更多信息"^]



=== 支持在删除卷之前备份

现在、您可以在删除卷之前对其进行备份。备份将保留在文件系统中、直到删除为止。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/delete-volume.html["删除卷"^]



== 2024 年 8 月 4 日



=== Terraform支持

现在、您可以使用CodeBox中的Terraform部署文件系统和Storage VM。

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["创建文件系统"^]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-storage-vm.html["创建Storage VM"^]
* link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html["使用CodeBox中的Terraform"^]




=== 存储计算器中的吞吐量和IOPS建议

存储计算器会根据AWS最佳实践为FSx for ONTAP文件系统的吞吐量和IOPS提供建议、从而为您的选择提供最佳指导。



== 2024年7月7日



=== Workload Factory for Amazon FSx for NetApp ONTAP的初始版本

Amazon FSx for NetApp ONTAP现已在Workload Factory中全面上市。
